### ISSUE TITLE
HBaseTableCatalog.newTable not working

### ISSUE THREAD

**Issue by khampson** [hortonworks-spark/shc#105]
Hi:

I am in the process of exploring shc to perform analysis/ETL of data we have in HBase using Spark. I have been able to read data in and transform it successfully, and am now attempting to write the data back to HBase in a different table.

I have a `DataFrame` which I wish to write out to an HBase table called **test_write_test**. That table doesn't currently exist, so I used the `HbaseTableCatalog.newTable` option so shc will create it. However, it doesn't appear to have any effect. There are no errors saying that it couldn't be created, but the Spark job ends up erroring out because HBase couldn't find the table **test_write_test**, meaning that either the table creation failed silently or it was never attempted in the first place.

Here is the code I'm using to attempt the table creation and write:
`        sqlRes.write.options(
                Map(HBaseTableCatalog.tableCatalog -> catalogTestWrite, HBaseTableCatalog.newTable -> "3"))
        .format("org.apache.spark.sql.execution.datasources.hbase")
        .save()`

If I precreate the table in HBase using hbase shell and then re-run the Spark job without the `HBaseTableCatalog.newTable` option, the write itself works. But I would like to have the flexibility for shc to create the table on the fly.

Some background: I am using:

1. shc's 2.1 branch which I built as per the instructions
2. HDP 2.4.2
3. Spark 2.1.0

I'm including both shc and Spark as dependencies during build time -- Spark is provided and running in a YARN container on our Hadoop cluster.

Thanks,
Ken

**Comment by weiqingy** [comment]
Hi, @khampson You may want to change the number `3` in the ` HBaseTableCatalog.newTable -> "3"` to any number `> 3`. The code [here](https://github.com/hortonworks-spark/shc/blob/master/core/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseRelation.scala#L117)  asks users to set up `newTable` to bigger than 3. For why there is a magic number `3`, please refer the [issue thread #76](https://github.com/hortonworks-spark/shc/issues/76) . 

Thanks.

**Comment by khampson** [comment]
@weiqingy : Thanks for the quick response! I tried it with 5 regions, and it worked.

I will work on creating a PR to supply an error message. My initial thought on that would be to throw a custom exception with an appropriate error message if `catalog.numReg <= 3`.

**Comment by weiqingy** [comment]
Yes, `custom exception with an appropriate error message` is good. I'll merge it once you submit the PR. Thanks.

**Comment by khampson** [comment]
Great. Thanks!

**Comment by adamdec** [comment]
What is the purpose of this check:

`if (catalog.numReg > 3) {`

Also if the user does not have permissions to create namespace in HBase...than table creation code will result in exception:

```
Caused by: org.apache.hadoop.hbase.ipc.RemoteWithExtrasException(org.apache.hadoop.hbase.security.AccessDeniedException): org.apache.hadoop.hbase.security.AccessDeniedException: Insufficient permissions (user=USER_NAME, scope=NAMESPACE, params=[namespace=NAMESPACE],action=ADMIN)
        at org.apache.hadoop.hbase.security.access.AccessController.requireNamespacePermission(AccessController.java:602)
        at org.apache.hadoop.hbase.security.access.AccessController.preGetNamespaceDescriptor(AccessController.java:1383)
        at org.apache.hadoop.hbase.master.MasterCoprocessorHost$7.call(MasterCoprocessorHost.java:170)
        at org.apache.hadoop.hbase.master.MasterCoprocessorHost.execOperation(MasterCoprocessorHost.java:1142)
        at org.apache.hadoop.hbase.master.MasterCoprocessorHost.preGetNamespaceDescriptor(MasterCoprocessorHost.java:166)
        at org.apache.hadoop.hbase.master.HMaster.getNamespaceDescriptor(HMaster.java:2554)
        at org.apache.hadoop.hbase.master.MasterRpcServices.getNamespaceDescriptor(MasterRpcServices.java:817)
        at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:55732)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2170)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:109)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:185)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:165)

        at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1269)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
        at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$BlockingStub.getNamespaceDescriptor(MasterProtos.java:58851)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation$5.getNamespaceDescriptor(ConnectionManager.java:2130)
        at org.apache.hadoop.hbase.client.HBaseAdmin$36.call(HBaseAdmin.java:2893)
        at org.apache.hadoop.hbase.client.HBaseAdmin$36.call(HBaseAdmin.java:2890)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
        ... 33 more
```

**Comment by khampson** [comment]
The user the job was running as had permission to create tables.

**Comment by khampson** [comment]
I created a PR: https://github.com/hortonworks-spark/shc/pull/106

**Comment by weiqingy** [comment]
PR has been merged, so close this. Thanks.

**Comment by AtulKumVerma** [comment]
Hi @weiqingy,
Can i use SHC for performing Hbase read/write using java

**Comment by weiqingy** [comment]
@AtulKumVerma Yes. SHC can work in any language supported by Spark.

**Comment by sharatexcelr** [comment]
Hi, 
Please can you confirm if I can use the same in sparkR.
As iam facing below error when passing the argument: HBaseTableCatalog.newTable
write.df(df, source = "org.apache.spark.sql.execution.datasources.hbase", mode = "append", catalog = catalog, HBaseTableCatalog.newTable -> "5")
Error in .local(df, path, ...) : 
  object 'HBaseTableCatalog.newTable' not found

And If the argument is not passed then I get another error:
write.df(df, source = "org.apache.spark.sql.execution.datasources.hbase", mode = "append", catalog = catalog)

Error: Error in save : org.apache.spark.sql.execution.datasources.hbase.InvalidRegionNumberException: Number of regions specified for new table must be greater than 3.
