### ISSUE TITLE
Caused by: java.lang.Exception: unsupported data type ARRAY

### ISSUE THREAD

**Issue by mavencode01** [hortonworks-spark/shc#132]
I have been stuck trying to figure if am doing something wrong but basically, I'm trying to use avro to writes data into hbase using your library but it's given me the error below:

Here is what my schema looks like:
```
player_schema = """
                    {
                        "type":"array",
                        "items": {
                            "name":"activities",
                            "type":"record",
                            "fields":[
                                    {"name":"start", "type":"double"},
                                    {"name":"y", "type":"double"},
                                    {"name":"width", "type":"double"}
                                ]
                            }
                    }
                 """     

opponent_schema = """
                {
                    "type":"array",
                    "items": {
                        "name":"opponent",
                        "type":"record",
                        "fields":[
                                {"name":"x", "type":"double"},
                                {"name":"y", "type":"double"}
                            ]
                        }
                }                    
         """       

```
Finally,

```

catalog = """{
                "table":{"namespace":"default", "name":"nhp_drake"},
                "rowkey":"id",
                "columns":{                
                    "id":{"cf":"rowkey", "col":"id", "type":"string"},
                    "feature":{"cf":"data", "col":"feature", "type":"string"},
                    "player":{"cf":"data", "col":"player", "avro":"player_schema"},
                    "opponent":{"cf":"data", "col":"opponent", "avro":"opponent_schema"}
                }
            }"""

df_drake_json.write.options(player_schema =player_schema, opponent_schema = opponent_schema, catalog = catalog).format("org.apache.spark.sql.execution.datasources.hbase").save()


```

```
Caused by: java.lang.Exception: unsupported data type ARRAY
        at org.apache.spark.sql.execution.datasources.hbase.AvroSedes$.serialize(SchemaConverters.scala:400)
        at org.apache.spark.sql.execution.datasources.hbase.Utils$.toBytes(Utils.scala:74)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$2.apply(HBaseRelation.scala:155)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$2.apply(HBaseRelation.scala:154)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1(HBaseRelation.scala:154)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$insert$1.apply(HBaseRelation.scala:161)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$insert$1.apply(HBaseRelation.scala:161)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1112)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1277)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1119)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1091)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
```

**Comment by mavencode01** [comment]
@weiqingy  Is this Avro schema example actually working?, I can't get the array type to work please.

```
val schema_array = s"""{"type": "array", "items": ["string","null"]}""".stripMargin
val schema_record =
  s"""{"namespace": "example.avro",
     |   "type": "record",      "name": "User",
     |    "fields": [      {"name": "name", "type": "string"},
     |      {"name": "favorite_number",  "type": ["int", "null"]},
     |        {"name": "favorite_color", "type": ["string", "null"]}      ]    }""".stripMargin
val catalog = s"""{
        |"table":{"namespace":"default", "name":"htable"},
        |"rowkey":"key1",
        |"columns":{
          |"col1":{"cf":"rowkey", "col":"key1", "type":"double"},
          |"col2":{"cf":"cf1", "col":"col1", "avro":"schema_array"},
          |"col3":{"cf":"cf1", "col":"col2", "avro":"schema_record"},
          |"col4":{"cf":"cf1", "col":"col3", "type":"double"},
          |"col5":{"cf":"cf1", "col":"col4", "type":"string"}
        |}
      |}""".stripMargin
 val df = sqlContext.read.options(Map("schema_array"->schema_array,"schema_record"->schema_record, HBaseTableCatalog.tableCatalog->catalog)).format("org.apache.spark.sql.execution.datasources.hbase").load()
df.write.options(Map("schema_array"->schema_array,"schema_record"->schema_record, HBaseTableCatalog.tableCatalog->catalog)).format("org.apache.spark.sql.execution.datasources.hbase").save()
```

**Comment by mavencode01** [comment]
It seems Array is not currently being supported 
https://github.com/zhzhan/shc/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/SchemaConverters.scala#L386

**Comment by weiqingy** [comment]
Hi, @mavencode01 Avro schema example works fine. Which SHC version you are using?

**Comment by mavencode01** [comment]
Thank you @weiqingy I just compiled the master branch and it works fine now.

Is any plans to publish this package to the repository?

**Comment by weiqingy** [comment]
We'll publish v1.1.0 to Hortonworks public repo ASAP.  Did you try the release versions (https://github.com/hortonworks-spark/shc/releases) which are more stable than the branches? v1.1.0 has supported all the Avro schemas.

**Comment by mavencode01** [comment]
Yeah I compiled that and it worked now - thank you.

Just a quick unrelated question to this but am sure you probably have an answer
Is Array type supported without using an Avro schema?

I tried but got this exception:

```
Caused by: java.lang.UnsupportedOperationException: PrimitiveType coder: unsupported data type WrappedArray([1.9796095151877942,0.1564485056196041,968.0], [2.1360580208073983,0.1564485056196041,89
        at org.apache.spark.sql.execution.datasources.hbase.types.PrimitiveType.toBytes(PrimitiveType.scala:61)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$1.apply(HBaseRelation.scala:221)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$1.apply(HBaseRelation.scala:217)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1(HBaseRelation.scala:217)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$insert$1$$anonfun$apply$4.apply(HBaseRelation.scala:229)
        at 
```

**Comment by weiqingy** [comment]
Right now, yes, PrimitiveType does not support Array type, but you can write your own data coder/decoder to support Array type (refer [SHCDataType](https://github.com/hortonworks-spark/shc/blob/master/core/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/types/SHCDataType.scala#L54)).

**Comment by mavencode01** [comment]
Cool...good to know - thank you once again @weiqingy

**Comment by weiqingy** [comment]
NP :)

**Comment by weiqingy** [comment]
Hi, @mavencode01 For Array, only Array[Byte] is supported by [all SHC dataType (data coders)](https://github.com/hortonworks-spark/shc/tree/master/core/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/types).

**Comment by mavencode01** [comment]
@weiqingy I'm wondering if it's possible to wrap the all columns as an Avro record instead of doing it per field?

**Comment by weiqingy** [comment]
I think it should work. :)

**Comment by mavencode01** [comment]
@weiqingy what would the catalog look like then?

```
val catalog = s"""{
        |"table":{"namespace":"default", "name":"htable"},
        |"rowkey":"key1",
        |"columns":{
          |"col1":{"cf":"rowkey", "col":"key1", "type":"double"},
          |"col2":{"cf":"cf1", "col":"data", "avro":"big_avro_record"}
        |}
      |}""".stripMargin
```

**Comment by weiqingy** [comment]
Yes. You can put all all columns into `big_avro_record`.

**Comment by mavencode01** [comment]
@weiqingy I tried that but no luck

basically, my schema looks like this:

```
# root
#  |-- feature: string (nullable = true)
#  |-- player: array (nullable = true)
#  |    |-- element: struct (containsNull = true)
#  |    |    |-- start: double (nullable = true)
#  |    |    |-- width: double (nullable = true)
#  |    |    |-- y: double (nullable = true)
#  |-- opponet: array (nullable = true)
#  |    |-- element: struct (containsNull = true)
#  |    |    |-- x: double (nullable = true)
#  |    |    |-- y: double (nullable = true)
#  |-- id: string (nullable = false)
```
Avro schema skipped here

Finally, my catalog something like this
```
val catalog = s"""{
        |"table":{"namespace":"default", "name":"htable"},
        |"rowkey":"key1",
        |"columns":{
          |"col1":{"cf":"rowkey", "col":"key1", "type":"double"},
          |"col2":{"cf":"cf1", "col":"data", "avro":"big_avro_record"}
        |}
      |}""".stripMargin
```
But am getting below exception:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o37.save.
: java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$.apply(HBaseTableCatalog.scala:259)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:80)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:59)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:426)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mavencode01** [comment]
Updated the exception

**Comment by mavencode01** [comment]
@weiqingy I got a step further by restructuring the dataframe into two column [id, data]

But seems this is not yet supported 

```
: org.apache.spark.sql.execution.datasources.hbase.types.SchemaConversionException: This mix of union types is not supported (see README): ArrayBuffer(ARRAY)
```

**Comment by weiqingy** [comment]
Hi, @mavencode01 

Maybe you can try to covert `big_avro_record` to `binary` first just like what AvroHBaseRecord example does [here](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/AvroSource.scala#L59) , then use `binary` type in the catalog definition like [here](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/AvroSource.scala#L70).

**Comment by mavencode01** [comment]
@weiqingy quick follow on that:
Can I use a dataframe/rdd instead of `GenericData.Record(avroSchema)`

```
    val user = new GenericData.Record(avroSchema)
    user.put("name", s"name${"%03d".format(i)}")
    user.put("favorite_number", i)
    user.put("favorite_color", s"color${"%03d".format(i)}")
    val favoriteArray = new GenericData.Array[String](2, avroSchema.getField("favorite_array").schema())
    favoriteArray.add(s"number${i}")
    favoriteArray.add(s"number${i+1}")
    user.put("favorite_array", favoriteArray)
    import collection.JavaConverters._
    val favoriteMap = Map[String, Int](("key1" -> i), ("key2" -> (i+1))).asJava
    user.put("favorite_map", favoriteMap)
    val avroByte = AvroSerde.serialize(user, avroSchema)
```

**Comment by weiqingy** [comment]
You can try, but I am afraid you could not use dataframe/rdd directly here since you need to invoke AvroSerde.serialize() which controls how to convert your data into binary. It means, take `AvroSerde.serialize(user, avroSchema)` as an example, Avro needs to understand what `user` is. 

You can refer [here](https://github.com/hortonworks-spark/shc/blob/master/core/src/test/scala/org/apache/spark/sql/AvroRecordSuite.scala#L32) to try to use `SchemaConverters.createConverterToSQL(avroSchema)(data) `and `SchemaConverters.toSqlType(avroSchema)` to convert `dataframe/rdd` to/from  Avro `Record`, I am not sure though.
