### ISSUE TITLE
: java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;

### ISSUE THREAD

**Issue by sa255304** [hortonworks-spark/shc#147]
f = sqlContext.read.options(catalog=catalog).format("org.apache.spark.sql.execution.datasources.hbase").load()
  File "/usr/hdp/2.5.3.16-1/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 139, in load
  File "/usr/hdp/2.5.3.16-1/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/hdp/2.5.3.16-1/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 45, in deco
  File "/usr/hdp/2.5.3.16-1/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o48.load.
: java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$.apply(HBaseTableCatalog.scala:280)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:77)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:51)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)

 
I cannot paste the exact code which i am using. So i am showing the code with dummy table names and table values.

 
catalog = ''.join("""{
    "table":{"namespace":"default", "name":"testtable"},
    "rowkey":"key",
    "columns":{
        "col0":{"cf":"rowkey", "col":"key", "type":"string"},
        "col1":{"cf":"cf", "col":"col1", "type":"string"}
    }
}""".split())

In the table name and namespace name i am using my project table details.

df = sqlContext.read.options(catalog=catalog).format("org.apache.spark.sql.execution.datasources.hbase").load()
 

I am using latest shc-core jar i.e.,  com.hortonworks:shc-core:1.1.1-2.1-s_2.11.. passing hbase , phoneix jars , hbase-site.xml and kerberos principal and keytab 

We are working in HDP 2.5.3 cluster , Spark version 1.6.2 and Hbase 1.1.2. 

Please let me know the fix for this Code?

**Comment by weiqingy** [comment]
For Spark version 1.6.x, you should use  com.hortonworks:shc-core:1.1.1-1.6-s_2.10.
For Spark version 2.1.x, you should use  com.hortonworks:shc-core:1.1.1-2.1-s_2.11.

**Comment by sa255304** [comment]
Still Facing Zookeeper and phoenix Excceptions in the code. I am Passing hbase-site.xml , hive-site.xml in --files and all Phoenix , Hbase Jars and SHC-Core jars in --jars command ..Setting the SHC credentails also. Using Project Prinicipal and Keytab in conf.set() command in pyspark code.

I am not getting what is the exact error. It is not the same Error Which mentioned  github page of SHC Reademe.md file. It is different

Could you please guide how to execute in Yarn-Cluster mode

**Comment by weiqingy** [comment]
For yarn-cluster mode, you may want to set Prinicipal and Keytab in command line or spark-defaults.xml.

**Comment by hamzaezzi** [comment]
I had, the same issue. (im using com.hortonworks:shc-core:1.1.1-1.6-s_2.10 with Spark 1.6.2)
The compiled library contain two versions of scala 2.10 and scala 2.11 (the dependence of spark-core with 2.11)
The library compiled with spark_core with scala 2.11 instead of scala 2.10
I recompiled the library with scala 2.10 and it works fine, I no longer have the issue...

    mvn clean package -P scala-2.10 -DskipTests

cordially

**Comment by vyshaliN** [comment]
I have the spark version as 2.1.0 and scala version as 2.11.8 But still I'm getting the error.Let me know if I'm missing anything
