### ISSUE TITLE
Does this connector support hbase 1.2.0? java.lang.NoSuchMethodError: org.apache.hadoop.hbase.client.Scan.setCaching(I)Lorg/apache/hadoop/hbase/client/Scan

### ISSUE THREAD

**Issue by Herry-JWong** [hortonworks-spark/shc#154]
I use Spark 2.1.0 and Hbase 1.2.0, when i read data from Hbase, i got following error:
17/07/03 16:54:44 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, uat-cdh07, executor 1): java.lang.NoSuchMethodError: org.apache.hadoop.hbase.client.Scan.setCaching(I)Lorg/apache/hadoop/hbase/client/Scan;
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD.org$apache$spark$sql$execution$datasources$hbase$HBaseTableScanRDD$$buildScan(HBaseTableScan.scala:223)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD$$anonfun$8.apply(HBaseTableScan.scala:280)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD$$anonfun$8.apply(HBaseTableScan.scala:279)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD.compute(HBaseTableScan.scala:279)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by weiqingy** [comment]
You may need to change the hbase version [in the pom.xml](https://github.com/hortonworks-spark/shc/blob/branch-2.1/pom.xml), and rebuild SHC with `mvn clean -DskipTests package`. The release versions in Hortonworks repo were built with hbase 1.1.2.

**Comment by Herry-JWong** [comment]
@weiqingy Thanks, i change the hbase version to 1.2.0-cdh5.11.0 inthe pom.xml and it works, because my cluseter is base on CDH5.

**Comment by sshanmuga** [comment]
@Herry-JWong , Are you sure **1.2.0-cdh5.11.0** is the only change?? I am getting exception while compiling ...

**Comment by weibingo** [comment]
@Herry-JWong , i also use 1.2.0-cdh5.11.0, but runtime still error.

**Comment by harryprince** [comment]
@Herry-JWong same issue + 1

**Comment by sourabh11** [comment]
> @weiqingy Thanks, i change the hbase version to 1.2.0-cdh5.11.0 inthe pom.xml and it works, because my cluseter is base on CDH5.

@weiqingy / @Herry-JWong : Can you please suggest be how to change version to 1.2.0-cdh5.11.0 in pom(my project POM?), I am also getting same error at CDH5.15.1 (where Hbase is 1.2.0), I am using below dependency,
              <dependency>
			<groupId>com.hortonworks</groupId>
			<artifactId>shc-core</artifactId>
			<version>1.2.0-2.1-s_2.11</version>  
		</dependency>

when I change it to 
<dependency>
    <groupId>org.apache.hbase</groupId>
    <artifactId>hbase-spark</artifactId>
    <version>1.2.0-cdh5.15.0</version>
</dependency>

, Hbase catalog API at code level showing compile time error, Is there any straight forward maven dependency available for CDH-5.15.1+ where Hbase is 1.2.0 , for shc-core API
Please help or mail me at < mehtasourabh11@gmail.com>

**Comment by nurikk** [comment]
@sourabh11 please do following actions

```bash
cd shc
git checkout origin/branch-2.3
```
and then apply patch

```
diff --git a/pom.xml b/pom.xml
index 4a4390e..f637e53 100644
--- a/pom.xml
+++ b/pom.xml
@@ -43,7 +43,8 @@

   <properties>
     <spark.version>2.3.0</spark.version>
-    <hbase.version>1.1.2</hbase.version>
+    <hbase.version>1.2.0-cdh5.14.2</hbase.version>
     <phoenix.version>4.9.0-HBase-1.1</phoenix.version>
     <test_classpath_file>${project.build.directory}/spark-test-classpath.txt</test_classpath_file>
     <java.version>1.7</java.version>
@@ -88,6 +89,18 @@
         <enabled>false</enabled>
       </snapshots>
     </repository>
+
+    <repository>
+      <id>cloudera-repo</id>
+      <name>Internal Repository</name>
+      <url>https://repository.cloudera.com/artifactory/cloudera-repos</url>
+      <releases>
+        <enabled>true</enabled>
+      </releases>
+      <snapshots>
+        <enabled>false</enabled>
+      </snapshots>
+    </repository>
   </repositories>

   <dependencies>
```

**Comment by netanel246** [comment]
@nurikk I've tried your solution and it's not working.
I found that the **Cloudera repo URL** that working is:
```
<repository>
      <id>cloudera-repo-release</id>
      <name>Internal Repository</name>
      <url>https://repository.cloudera.com/content/repositories/releases/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
```

**Comment by mukesh14j** [comment]
m also facing same error. tried different hbase version too
anyone was able to solve it ?

**Comment by sourabh11** [comment]
Mukesh, what I have done for work around to solve this, to change cloudera
provided jar version explicitly, at default location like /var/lib/...
Reason for this error is cloudera always place it's own jar first than jar
provided by our job, if it is same, hence it conflicts to give this
nosuchmethod error

**Comment by mukesh14j** [comment]
Thanks sourabh, 
To be more precise u changed the hbase client version under cloudera to 1.2.0-cdh5.11.0. It works only with 1.2.0-cdh5.11.0 or any version above it?

**Comment by sourabh11** [comment]
Hi Mukesh,
It's been long time, I don't remember exactly the jar name, if you are
really stuck need help , then let me know, I have made note some where will
search for you.

**Comment by sourabh11** [comment]
Hi Mukesh,
 I found pointers ,what I did that time, It may help you


###########
1. mv hbase-client-1.2.0-cdh5.14.4.jar
hbase-client-1.2.0-cdh5.14.4.jar_bckup
2. placed my jar hbase-client-1.2.0.jar to above location with same name
and renamed exising jar



  reason : CDH provides it's own Hbase client api like below depenedncy ,
so when we use shc-core bundle , (it contains Hbase-client api for hbase
-1.1.2)
  this causes problem and causes api mismatch , as CDH over rules with it's
own existing API, hence we replaced CDH version of jars with open source
  Hbase-Client.jar (downloaded from maven) at same place.

###############
