### ISSUE TITLE
Inconsistent HBase row count

### ISSUE THREAD

**Issue by kings129** [hortonworks-spark/shc#174]
I am using shc to count HBase rows between certain time range, but I am seeing inconsistent row count result, rows with certain prefix bytes are missing from result.

My code:
........
df = sqlc.read.options(catalog=catalog, minStamp=1501459200000, maxStamp=1501462800000).format(data_source_format).load() 
df.registerTempTable("t") 
r1 = sqlc.sql("Select hex(substr(col0, 1, 2)) as shard, count(col0) from t where col0 > unhex
ex('0000') and col0 < unhex('0010') group by 1 order by 1")  

Output:
+-----+-----------+
|shard|count(col0)|
+-----+-----------+
| 0000|       2962|
| 0001|      69816|
| 0002|       1250|
| 0003|       2084|
| 0004|       2218|
| 0005|       2317|
| 0006|        587|
| 0007|       1028|
| 0008|      11279|
| 000A|       4219|
| 000B|       2020|
| 000C|       9652|
| 000D|       2350|
| 000E|       1707|
+-----+-----------+

As you can see, shard 0009 and shard 000F is missing, and this result is not consistent, other shard counts might be missing in another try. But if I narrow down sql scan range like, result is correct.
sqlc.sql("Select hex(substr(col0, 1, 2)) as shard, count(col0) from t where col0 > unhex
ex('000f') and col0 < unhex('0010') group by 1 order by 1")
+-----+-----------+
|shard|count(col0)|
+-----+-----------+
| 000F|       1382|
+-----+-----------+

Have you seen issue like this before? Any help is appreciated!

**Comment by weiqingy** [comment]
Hi @kings129 What SHC version you are using?

**Comment by kings129** [comment]
@weiqingy I was using master branch, compiled with spark.version 2.1.1 and hbase.version 1.2.0-cdh5.8.0.

**Comment by weiqingy** [comment]
Could you please try the following SHC versions:

```
 --packages com.hortonworks:shc-core:1.0.0-2.0-s_2.11 --repositories http://repo.hortonworks.com/content/groups/public/
```
and 

```
 --packages com.hortonworks:shc-core:1.1.0-2.1-s_2.11 --repositories http://repo.hortonworks.com/content/groups/public/
```
Please lets know if you still hit the issue. I want to check if there is a regression in master branch.

**Comment by kings129** [comment]
Hi @weiqingy , thanks for suggestion, I checked out corresponding commits for both versions and built with hbase.version 1.2.0-cdh5.8.0, unfortunately both of them had the same issue.

**Comment by kings129** [comment]
@weiqingy , I find following log from executor, timeout error didn't fail task and it returns 0. Which should be the root cause of wrong row count.

17/08/18 22:59:58 DEBUG LeaseRenewer: Lease renewed for client DFSClient_NONMAPREDUCE_1319730509_27
17/08/18 22:59:58 DEBUG LeaseRenewer: Lease renewer daemon for [DFSClient_NONMAPREDUCE_1319730509_27] with renew id 1 executed
17/08/18 23:00:02 TRACE RpcClientImpl: ignored
java.net.SocketTimeoutException: 20000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/*********** remote=********]
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readInt(DataInputStream.java:387)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.readResponse(RpcClientImpl.java:963)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.run(RpcClientImpl.java:566)
.......
INFO HBaseTableScanRDD: returned 0 rows from hbase in 30033 ms.

**Comment by kings129** [comment]
Fixed socket timeout by using a hbase flag, but issue still not fixed.

17/08/22 00:47:34 INFO HBaseTableScanRDD: returned 0 rows from hbase in 30024 ms

@weiqingy , I think there's another flag for hbase scan operation set to 30000 ms somewhere, trying to find it, please let me know if you have any clue. Thanks!

**Comment by weiqingy** [comment]
Thanks, @kings129 . I'll update here if having any updates. Could you share which flag you are using to fix this issue? It seems https://github.com/hortonworks-spark/shc/issues/175 also hit the timeout issue. cc: @tracyzl
