### ISSUE TITLE
How to get data in DataFrame from hbase using SHC without using Rdd

### ISSUE THREAD

**Issue by AtulKumVerma** [hortonworks-spark/shc#183]
Is there anyway to fetch data from hbase directly in dataframe without using rdd.

my code..

./bin/spark-shell --files file:///usr/local/hbase/conf/hbase-site.xml,file:///usr/local/hadoop/etc/hadoop/core-site.xml,file:///usr/local/hadoop/etc/hadoop/hdfs-site.xml --jars /home/ist/jarfile/shc-core-1.1.1-2.1-s_2.11.jar,/home/ist/jarfile/hbase-spark-2.0.0-alpha-1.jar,file:///home/ist/Downloads/hbase-client-1.3.0.jar,/home/ist/jarfile/hbase-0.94.2.jar,/home/ist/jarfile/hbase-common-0.98.3-hadoop1.jar,file:///home/ist/jarfile/hbase-protocol-0.95.0.jar,file:///home/ist/Downloads/hbase-spark-1.2.0-cdh5.7.3.jar

         import org.apache.spark.sql._
         import org.apache.spark.sql.datasources.hbase._
         import org.apache.spark.sql.execution.datasources.hbase._
         import org.apache.hadoop._
         import org.apache.hadoop.hbase.util._
          val sqlContext = new SQLContext(sc)
          
          def catalog = s"""{
             |"table":{"namespace":"default", "name":"table1"},
             |"rowkey":"key",
             |"columns":{
               |"col0":{"cf":"rowkey", "col":"key", "type":"string"},
               |"col1":{"cf":"cf1", "col":"col1", "type":"string"}
             |}
           |}""".stripMargin
           
        
         def withCatalog(cat: String): DataFrame = {
         sqlContext
        .read
        .options(Map(HBaseTableCatalog.tableCatalog->cat))
        .format("org.apache.spark.sql.execution.datasources.hbase")
        .load()
      }
      
		val df = withCatalog(catalog)
		
		df.printSchema()
		df.show()

but not getting any progress so plz help me out...
i got this Exception again n again 

java.io.IOException: java.lang.reflect.InvocationTargetException
  at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
  at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
  at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:141)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:141)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:132)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:130)
  at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
  at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$.getConnection(HBaseConnectionCache.scala:130)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$.getConnection(HBaseConnectionCache.scala:141)
  at org.apache.spark.sql.execution.datasources.hbase.RegionResource.init(HBaseResources.scala:93)
  at org.apache.spark.sql.execution.datasources.hbase.ReferencedResource$class.liftedTree1$1(HBaseResources.scala:57)
  at org.apache.spark.sql.execution.datasources.hbase.ReferencedResource$class.acquire(HBaseResources.scala:54)
  at org.apache.spark.sql.execution.datasources.hbase.RegionResource.acquire(HBaseResources.scala:88)
  at org.apache.spark.sql.execution.datasources.hbase.ReferencedResource$class.releaseOnException(HBaseResources.scala:74)
  at org.apache.spark.sql.execution.datasources.hbase.RegionResource.releaseOnException(HBaseResources.scala:88)
  at org.apache.spark.sql.execution.datasources.hbase.RegionResource.<init>(HBaseResources.scala:108)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD.getPartitions(HBaseTableScan.scala:61)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:311)
  at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
  at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2377)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2113)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2795)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2327)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:248)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:636)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:595)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:604)
  ... 58 elided
Caused by: java.lang.reflect.InvocationTargetException: java.lang.NoSuchMethodError: org.apache.hadoop.hbase.util.Addressing.getIpAddress()Ljava/net/InetAddress;
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
  ... 111 more
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.hbase.util.Addressing.getIpAddress()Ljava/net/InetAddress;
  at org.apache.hadoop.hbase.client.ClientIdGenerator.getIpAddressBytes(ClientIdGenerator.java:83)
  at org.apache.hadoop.hbase.client.ClientIdGenerator.generateClientId(ClientIdGenerator.java:43)

**Comment by weiqingy** [comment]
Please check the hbase version https://github.com/hortonworks-spark/shc/blob/branch-2.1/pom.xml#L46. If you want to use other hbase versions instead of 1.1.2. You may need to change the hbase version number in SHC pom file and rebuild SHC jars. 
If hbase 1.1.2 also works for you, you can try this: 
```
./bin/spark-shell --files file:///usr/local/hbase/conf/hbase-site.xml --packages com.hortonworks:shc-core:1.1.1-2.1-s_2.11 --repositories http://repo.hortonworks.com/content/groups/public/
```

**Comment by AtulKumVerma** [comment]
Thanks for you reply now its work ...😃
now i want to write code in java and use this shc jar so plz let me know
how i did this wid any example

---
*Thanks & Regards*

*Er. Atul VermaStudent of CSE department.*

**Comment by weiqingy** [comment]
SHC is a Spark lib for users to access Hbase tables, so SHC can work in any language spark supports. In java, you just need to define the catalog in java syntax, then use Spark java dataframe APIs (or Spark sql in java) to read/write data into HBase.

**Comment by rashid-1989** [comment]
@weiqingy Could you please suggest an example of defining the schema in java. This [(https://github.com/hortonworks-spark/shc/blob/master/core/src/test/scala/org/apache/spark/sql/AvroKeySourceSuite.java)] has a catalog defined for avro files. I need to write a similar catalog for hbase read irrespective of file format.
