### ISSUE TITLE
unsupported data type null

### ISSUE THREAD

**Issue by AtulKumVerma** [hortonworks-spark/shc#185]
my code :

> String actualTableCatalog = "{\"table\":{\"namespace\":\"default\"\,\"name\":\"emp2\"}\,\"rowkey\":\"key\"\,\"columns\":{\"rowKey\":{\"cf\":\"rowkey\"\,\"col\":\"key\"\,\"type\":\"string\"}\,\"name\":{\"cf\":\"r\"\,\"col\":\"name\"\,\"type\":\"string\"}\,\"age\":{\"cf\":\"r\"\,\"col\":\"age\"\,\"type\":\"string\"}\,\"rollno\":{\"cf\":\"r\"\,\"col\":\"rollno\"\,\"type\":\"string\"}}}";
> 
> Map<String, String> catalog = new HashMap<String, String>();
> catalog.put(HBaseTableCatalog.tableCatalog(), actualTableCatalog);
> catalog.put(HBaseTableCatalog.newTable(), "1000");
> 
> this.dataFrame.write().options(catalog).format("org.apache.spark.sql.execution.datasources.hbase").save();

if i have dataFrame like this that contain null value and if i m going for HBase write then getting an issue like PrimitiveType coder: unsupported data type null
+------+-----+---+------+
|rowKey| name|age|rollno|
+------+-----+---+------+
|     1|piyuu| 24|    19|
|     2| Atul| 23|    18|
|     3|  xyz| 24|  null|
+------+-----+---+------+

Exception : 
java.lang.UnsupportedOperationException: PrimitiveType coder: unsupported data type null
	at org.apache.spark.sql.execution.datasources.hbase.types.PrimitiveType.toBytes(PrimitiveType.scala:61)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$1.apply(HBaseRelation.scala:221)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$1.apply(HBaseRelation.scala:217)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1(HBaseRelation.scala:217)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$insert$1$$anonfun$apply$4.apply(HBaseRelation.scala:229)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$insert$1$$anonfun$apply$4.apply(HBaseRelation.scala:229)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1124)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1123)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1123)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1341)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1131)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by weiqingy** [comment]
you can add null type [here](https://github.com/hortonworks-spark/shc/blob/master/core/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/types/PrimitiveType.scala#L40) (the following means doing nothing):
``
 case null => 
``
Then rebuild SHC jar.

**Comment by sachinsga** [comment]
I did build the shc-core jar but there seems to be no change. Getting the same exception. Please suggest how this can be taken care of.

**Comment by weiqingy** [comment]
@sachinsga https://github.com/hortonworks-spark/shc/pull/198 is for this issue.

**Comment by weiqingy** [comment]
Fixed by #198 . Close this.
