### ISSUE TITLE
Can't smallint and tinyint data type be supported well in SHC 1.1.1-2.1-s_2.11 with HBase 1.2.3?

### ISSUE THREAD

**Issue by ChenShuai1981** [hortonworks-spark/shc#189]
I tried the SHC README.md example with HBase 1.2.3 but found both "smallint" and "tinyint" data are not consistent between write and read. Following "col6" is smallint while "col8" is tinyint
write:
+----+-----+----+----+----+-------+----+----+----+
|col0| col1|col2|col3|col4|   col5|col6|col7|col8|
+----+-----+----+----+----+-------+----+----+----+
| foo|false|0.01| 0.3|   2|1234567|   3| abc|   1|
+----+-----+----+----+----+-------+----+----+----+

read:
+----+-----+----+----+----+-------+----+----+----+
|col0| col1|col2|col3|col4|   col5|col6|col7|col8|
+----+-----+----+----+----+-------+----+----+----+
| foo|false|0.01| 0.3|   2|1234567|   0| abc|   0|
+----+-----+----+----+----+-------+----+----+----+

Query data from Phoenix and mismatched
0: jdbc:phoenix:localhost> select * from "table1";
+------+--------+----------+--------+--------------+-----------------------+---------+-------+-------+
|  PK  |  col1  |   col2   |  col3  |     col4     |         col5          |  col6   | col7  | col8  |
+------+--------+----------+--------+--------------+-----------------------+---------+-------+-------+
| foo  | false  | -440.32  | -14.4  | -2147483646  | -9223372036853541241  | -32768  |       | -125  |
+------+--------+----------+--------+--------------+-----------------------+---------+-------+-------+

Here is the Phoenix DDL:  (My Phoenix Version is apache-phoenix-4.11.0-HBase-1.2-bin)
create view "table1" ( pk VARCHAR PRIMARY KEY, "cf1"."col1" BOOLEAN, "cf2"."col2" DOUBLE, "cf3"."col3" FLOAT, "cf4"."col4" INTEGER, "cf5"."col5" BIGINT, "cf6"."col6" SMALLINT, "cf7"."col7" VARCHAR, "cf8"."col8" TINYINT  );

Here is the code
def catalog = s"""{
                   |"table":{"namespace":"default", "name":"table1"},
                   |"rowkey":"key",
                   |"columns":{
                   |"col0":{"cf":"rowkey", "col":"key", "type":"string"},
                   |"col1":{"cf":"cf1", "col":"col1", "type":"boolean"},
                   |"col2":{"cf":"cf2", "col":"col2", "type":"double"},
                   |"col3":{"cf":"cf3", "col":"col3", "type":"float"},
                   |"col4":{"cf":"cf4", "col":"col4", "type":"int"},
                   |"col5":{"cf":"cf5", "col":"col5", "type":"bigint"},
                   |"col6":{"cf":"cf6", "col":"col6", "type":"smallint"},
                   |"col7":{"cf":"cf7", "col":"col7", "type":"string"},
                   |"col8":{"cf":"cf8", "col":"col8", "type":"tinyint"}
                   |}
                   |}""".stripMargin

  case class Foobar(col0: String, col1: Boolean, col2: Double, col3: Float, col4: Integer,
                    col5: Long, col6: Integer, col7: String, col8: Integer)

  val foobarRdd = sparkContext.parallelize(("foo", false, 0.01, 0.3f, 2, 1234567L, 3, "abc", 1) :: Nil).
    map { case (col0, col1, col2, col3, col4, col5, col6, col7, col8) => Foobar(col0, col1, col2, col3, col4, col5, col6, col7, col8) }

  import sqlContext.implicits._

  val foobarDf = foobarRdd.toDF
  foobarDf.limit(1).show

  foobarDf.write.options(
    Map(HBaseTableCatalog.tableCatalog -> catalog, HBaseTableCatalog.newTable -> "5"))
    .format("org.apache.spark.sql.execution.datasources.hbase")
    .save()

  def withCatalog(cat: String): DataFrame = {
    sqlContext
      .read
      .options(Map(HBaseTableCatalog.tableCatalog->cat))
      .format("org.apache.spark.sql.execution.datasources.hbase")
      .load()
  }

  val df = withCatalog(catalog)
  //SQL example
  df.createOrReplaceTempView("table")
  sqlContext.sql("select * from table").show

Then I upgrade SHC HBase dependency from 1.1.1 to 1.2.3 and rerun program then found the following exception:

Exception in thread "main" java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:144)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:144)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:135)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:133)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$.getConnection(HBaseConnectionCache.scala:133)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$.getConnection(HBaseConnectionCache.scala:144)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.createTableIfNotExist(HBaseRelation.scala:126)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:64)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:457)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
	at com.geerong.nebula.stream.sink.SHCExample$.delayedEndpoint$com$geerong$nebula$stream$sink$SHCExample$1(SHCExample.scala:45)
	at com.geerong.nebula.stream.sink.SHCExample$delayedInit$body.apply(SHCExample.scala:9)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.geerong.nebula.stream.sink.SHCExample$.main(SHCExample.scala:9)
	at com.geerong.nebula.stream.sink.SHCExample.main(SHCExample.scala)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
	... 25 more
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/types/CopyOnWriteArrayMap
	at org.apache.hadoop.hbase.client.MetaCache.<init>(MetaCache.java:52)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:714)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:643)
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.types.CopyOnWriteArrayMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more

<dependency>
      <groupId>com.hortonworks</groupId>
      <artifactId>shc-core</artifactId>
      <version>1.2.3-2.2-s_2.11-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hbase</groupId>
      <artifactId>hbase-client</artifactId>
      <version>1.2.3</version>
    </dependency>

**Comment by weiqingy** [comment]
Did your case with HBase 1.1.2 also hit the issue?
