### ISSUE TITLE
JSON format of HBase configuration

### ISSUE THREAD

**Issue by souvik82** [hortonworks-spark/shc#195]
What is the JSON format for HBase configuration as I am getting below error:

Please suggest me what is root cause of this error? Below is my command

**spark-shell --packages com.hortonworks:shc-core:1.1.1-1.6-s_2.10 --repositories http://repo.hortonworks.com/content/groups/public/ --files /usr/iop/4.2.0.0/hbase/conf/hbase-site.xml**

Caused by: java.lang.NullPointerException
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.getMetaReplicaNodes(ZooKeeperWatcher.java:395)
        at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:553)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1185)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1152)
        at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:300)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:151)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:59)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)

**Comment by weiqingy** [comment]
You may want to copy the hbase-site.xml to spark conf folder.

**Comment by souvik82** [comment]
As per this link [JoinTablesFrom2Clusters](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/JoinTablesFrom2Clusters.scala), how can we pass conf string to this below function
`def withCatalog(cat: String, conf: String): DataFrame = {
      sqlContext
        .read
        .options(Map(HBaseTableCatalog.tableCatalog->cat, HBaseRelation.HBASE_CONFIGFILE -> conf))
        .format("org.apache.spark.sql.execution.datasources.hbase")
        .load()
    }`

Can you please provide me the sample JSON file?

**Comment by souvik82** [comment]
Thanks for your support. It's working...
