### ISSUE TITLE
Spark 2.1.x  java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by mavencode01** [hortonworks-spark/shc#202]
@weiqingy I'm trying to read and write to hbase using shc `com.hortonworks:shc-core:1.1.1-2.1-s_2.11` version on spark 2.1.x  but got an exception relating to class def not found error.

Looks like it's missing hbase-protocal library

```
py4j.protocol.Py4JJavaError: An error occurred while calling o58.save.
 java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.Class.forName0(Native Method)
       at java.lang.Class.forName(Class.java:264)
       at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:228)
       at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
       at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
       at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:141)
       at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:141)
       at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:132)
       at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:130)
       at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
       at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
       at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$.getConnection(HBaseConnectionCache.scala:130)
```

Is there a way to fix this?

Thanks

**Comment by weiqingy** [comment]
What is the HBase version in your cluster? SHC is using HBase [<hbase.version>1.1.2</hbase.version>](https://github.com/hortonworks-spark/shc/blob/master/pom.xml#L46).

**Comment by mavencode01** [comment]
I'm using HBase `1.2.0-cdh5.8.2` which works fine with SHC and spark 1.6 version

**Comment by empire1601** [comment]
Good morning,

I have the same issu with shc-core-1.0.1-2.0-s_2.11, pyspark, HDP-2.5.3.0
I'm using your package on a cluster with no connection with horton repositorie. So I should add manually dependencies : 
`spark-submit
--master yarn
--conf spark.driver.extraClassPath=$root_dir/jar/shc-core-1.1.1-2.0-s_2.11-SNAPSHOT.jar:$root_dir/jar/hbase-client-1.1.2.2.5.3.0-37.jar:$root_dir/jar/hbase-common-1.1.2.2.5.3.0-37.jar:$root_dir/jar/hbase-server-1.1.2.2.5.3.0-37.jar:$root_dir/jar/hbase-testing-util-1.1.2.2.5.3.0-37.jar \
--conf spark.executor.extraClassPath=$root_dir/jar/shc-core-1.1.1-2.0-s_2.11-SNAPSHOT.jar:$root_dir/jar/hbase-client-1.1.2.2.5.3.0-37.jar:$root_dir/jar/hbase-common-1.1.2.2.5.3.0-37.jar:$root_dir/jar/hbase-server-1.1.2.2.5.3.0-37.jar:$root_dir/jar/hbase-testing-util-1.1.2.2.5.3.0-37.jar \
--files /usr/hdp/current/hbase-client/conf/hbase-site.xml \
--jars $root_dir/jar/shc-core-1.1.1-2.0-s_2.11-SNAPSHOT.jar \
--jars $root_dir/jar/hbase-common-1.1.2.2.5.3.0-37.jar \
--jars $root_dir/jar/hbase-client-1.1.2.2.5.3.0-37.jar \
--jars $root_dir/jar/hbase-server-1.1.2.2.5.3.0-37.jar \
--jars $root_dir/jar/hbase-testing-util-1.1.2.2.5.3.0-37.jar \
myscript.py`

and the error : 
`  [sshexec] Traceback (most recent call last):
  [sshexec]   File "/home/c59rbru/delivery/profilage/calcul/it4/profilage_main.py", line 88, in <module>
  [sshexec]     expo_db.saveHbase("profil", "nir")
  [sshexec]   File "/home/c59rbru/delivery/profilage/calcul/it4/spark_common/spark_api.zip/database/database.py", line 183, in saveHbase
  [sshexec]   File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 545, in save
  [sshexec]   File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  [sshexec]   File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  [sshexec]   File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
  [sshexec] py4j.protocol.Py4JJavaError: An error occurred while calling o207.save.
  [sshexec] : java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface
  [sshexec] 	at java.lang.Class.forName0(Native Method)
  [sshexec] 	at java.lang.Class.forName(Class.java:264)
  [sshexec] 	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:228)
  [sshexec] 	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
  [sshexec] 	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
  [sshexec] 	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:141)
  [sshexec] 	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$getConnection$1.apply(HBaseConnectionCache.scala:141)
  [sshexec] 	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:132)
  [sshexec] 	at org.apache.spark.sql.execution.datasources.hbase.HBaseConnectionCache$$anonfun$1.apply(HBaseConnectionCache.scala:130)
  [sshexec] 	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
  [sshexec] 	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)`

Thank you for your help

Rémi Bruyère

**Comment by empire1601** [comment]
I've solved it by adding `hbase-protocol-1.1.2.2.5.3.0-37.jar`, if it cant help.
