### ISSUE TITLE
shc example fails env(Scala 2.10, Spark 1.6.0,   "zhzhan" % "shc" % "0.0.11-1.6.1-s_2.10")

### ISSUE THREAD

**Issue by manasdebashiskar** [hortonworks-spark/shc#212]
Hi , 
 I can use some help for shc example code.

I have the same code with the following dependencies 
```
lazy val libs = Seq(
    "org.apache.spark" %% "spark-core" % "1.6.0" % "provided",
    "org.apache.spark" %% "spark-sql" % "1.6.0" % "provided",
    "org.scalatest" %% "scalatest" % "2.2.4" % "test",
    //"com.hortonworks" % "shc" % "1.0.0-1.6-s_2.10",
    "zhzhan" % "shc" % "0.0.11-1.6.1-s_2.10"
)

```
The code seems to be failing on my cloudera VM with the following error
```
Exception in thread "main" java.lang.AbstractMethodError
	at org.apache.spark.Logging$class.log(Logging.scala:50)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.log(HBaseRelation.scala:64)
	at org.apache.spark.Logging$class.logDebug(Logging.scala:62)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.logDebug(HBaseRelation.scala:64)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:96)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:94)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.createTable(HBaseRelation.scala:94)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:58)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.dataSource$lzycompute$1(DataFrameWriter.scala:181)
	at org.apache.spark.sql.DataFrameWriter.org$apache$spark$sql$DataFrameWriter$$dataSource$1(DataFrameWriter.scala:181)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$save$1.apply$mcV$sp(DataFrameWriter.scala:188)
	at org.apache.spark.sql.DataFrameWriter.executeAndCallQEListener(DataFrameWriter.scala:154)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:188)
	at com.economical.etl.Extractor$.main(Extractor.scala:90)
	at com.economical.etl.Extractor.main(Extractor.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:730)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

Can someone please guide me in the right direction?

Thanks
..Manas

**Comment by weiqingy** [comment]
Could you try the versions published into Hortonowork repo: 
For spark 1.6.x:
```
--packages com.hortonworks:shc-core:1.1.1-1.6-s_2.10 --repositories http://repo.hortonworks.com/content/groups/public/ 
```

**Comment by manasdebashiskar** [comment]
Hi @weiqingy , 
 Thanks for getting back to me. For some reason I did not get notified about your reply.
Yes, I have also tried the following steps.

`git clone	https://github.com/hortonworks-spark/shc.git `
`cd shc`
`git checkout tags/v1.1.1-1.6 -b v1.1.1-1.6`
`mvn clean package -Pscala-2.10 -DskipTests` _Please note that by default it builds it with scala 2.11 and still creates a jar with name **_2.10**. Which in turn causes problem while launching it with spark 1.6_2.10_
```
spark-submit --verbose --jars core/target/shc-core-1.1.1-1.6-s_2.10.jar \

--class org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource \

--master yarn \

--files /etc/hbase/conf/hdfs-site.xml \

examples/target/shc-examples-1.1.1-1.6-s_2.10.jar
```

The only thing worth noting here is that I am running it in a cloudera vm  `version 5.10.2.`
Other notable thing might help is 'JDK 1.8'

The above step seems to be causing an error. Stack trace is posted below.

```
Exception in thread "main" java.lang.AbstractMethodError
	at org.apache.spark.Logging$class.log(Logging.scala:50)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.log(HBaseRelation.scala:70)
	at org.apache.spark.Logging$class.logDebug(Logging.scala:62)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.logDebug(HBaseRelation.scala:70)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:147)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:145)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.createTable(HBaseRelation.scala:145)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:61)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource$.main(HBaseSource.scala:105)
	at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource.main(HBaseSource.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Please let me know if you see any discrepancy in your environment that might be causing the issue or if there is something else going on here.

.Manas

**Comment by manasdebashiskar** [comment]
Further to my question, I tried to stub out the spark logging part.
Now it seems that it is not able to find few of the classes that were created by the very application.
At this point, I feel may be it is a class loading problem.

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hbase.HTableDescriptor.addFamily(Lorg/apache/hadoop/hbase/HColumnDescriptor;)Lorg/apache/hadoop/hbase/HTableDescriptor;
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:148)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:145)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.createTable(HBaseRelation.scala:145)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:61)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.dataSource$lzycompute$1(DataFrameWriter.scala:181)
	at org.apache.spark.sql.DataFrameWriter.org$apache$spark$sql$DataFrameWriter$$dataSource$1(DataFrameWriter.scala:181)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$save$1.apply$mcV$sp(DataFrameWriter.scala:188)
	at org.apache.spark.sql.DataFrameWriter.executeAndCallQEListener(DataFrameWriter.scala:154)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:188)
	at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource$.main(HBaseSource.scala:105)
	at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource.main(HBaseSource.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:730)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by weiqingy** [comment]
What Hbase version you were using? SHC 1.6 is using  <hbase.version>1.1.2</hbase.version>

**Comment by manasdebashiskar** [comment]
Hi @weiqingy ,
 I am using Cloudera 5.10 which packages Hbase 1.2.0. 
 I did fiddle around with the dependencies and changed them to 1.2.0 but that also gives me the same issue.

**Comment by manasdebashiskar** [comment]
Hey @weiqingy A follow up questions since I still can't make it work with my cloudera VM is that, Is SHC 1.6 intended to work against `hbase.version=1.2.0`?

**Comment by weiqingy** [comment]
No. if you want to make SHC 1.6 against other hbase versions, you need to specify the version [here](https://github.com/hortonworks-spark/shc/blob/branch-1.6/pom.xml#L46), and build the corresponding SHC jar by yourself.

**Comment by manasdebashiskar** [comment]
Hi @weiqingy , 
 Thanks for getting back to me.
 Yes, I had gone ahead and done that. 

Here is another way to see this error by running it through spark-shell

```
 spark-shell --master local --jars core/target/shc-core-1.1.1-1.6-s_2.10.jar --jars examples/target/shc-examples-1.1.1-1.6-s_2.10.jar --class org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource --repositories http://repo.hortonworks.com/content/groups/public/ --files /etc/hbase/conf/hbase-site.xml --conf "spark.driver.userClassPathFirst=true"
```

The above command fails with the exact same error

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/datasources/hbase/HBaseTableCatalog$
        at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource$.main(HBaseSource.scala:103)
        at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource.main(HBaseSource.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$
        at java.lang.ClassLoader.findClass(ClassLoader.java:531)
        at org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.scala:26)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:34)
        at org.apache.spark.util.ChildFirstURLClassLoader.liftedTree1$1(MutableURLClassLoader.scala:75)
        at org.apache.spark.util.ChildFirstURLClassLoader.loadClass(MutableURLClassLoader.scala:71)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 11 more

```

**Comment by lionelcao** [comment]
You may need to package the core & example in one jar or import HBaseTableCatalog in the example class

**Comment by manasdebashiskar** [comment]
Hi @lionelcao 
Yes, I think you are right. 
I am going to give it a try and post the results.
What confuses me is though, how come I saw it and no one else seems to have complained about it.

**Comment by manasdebashiskar** [comment]
Here is the result.
 I tried a single jar using the dependency from `shc-core`.
 I am still getting the error which is given below.

At this point, I am not sure where to go from here..

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hbase.HTableDescriptor.addFamily(Lorg/apache/hadoop/hbase/HColumnDescriptor;)Lorg/apache/hadoop/hbase/HTableDescriptor;
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:151)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:146)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.createTable(HBaseRelation.scala:146)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:61)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
        at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource$.main(HBaseSource.scala:105)
        at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource.main(HBaseSource.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by mcamendoza1** [comment]
encountered same error 
any idea?
```
  <repositories>
    <repository>
      <id>central</id>
      <!-- This should be at top, it makes maven try the central repo first and then others and hence faster dep resolution -->
      <name>Maven Repository</name>
      <url>https://repo1.maven.org/maven2</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>apache-repo</id>
      <name>Apache Repository</name>
      <url>https://repository.apache.org/content/repositories/releases</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <!-- Cloudera Repo -->
    <repository>
      <id>cloudera</id>
      <url>https://repository.cloudera.com/artifactory/cloudera-repos/</url>
    </repository>
  </repositories>
```

```
 <properties>
    <spark.version>1.6.0-cdh5.8.4</spark.version>
    <hbase.version>1.2.0-cdh5.8.4</hbase.version>
    <phoenix.version>4.9.0-HBase-1.2</phoenix.version>
    <test_classpath_file>${project.build.directory}/spark-test-classpath.txt</test_classpath_file>
    <java.version>1.7</java.version>
    <scala.version>2.10.5</scala.version>
    <scala.macros.version>2.0.1</scala.macros.version>
    <scala.binary.version>2.10</scala.binary.version>
    <avro.version>1.7.6</avro.version>
    <codahale.metrics.version>3.0.0</codahale.metrics.version>
    <codehaus.jackson.version>1.8.8</codehaus.jackson.version>

    <PermGen>64m</PermGen>
    <MaxPermGen>512m</MaxPermGen>
    <CodeCacheSize>512m</CodeCacheSize>
  </properties>
```

```
Exception in thread "main" java.lang.AbstractMethodError
	at org.apache.spark.Logging$class.log(Logging.scala:50)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.log(HBaseRelation.scala:70)
	at org.apache.spark.Logging$class.logDebug(Logging.scala:62)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.logDebug(HBaseRelation.scala:70)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:147)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$createTable$1.apply(HBaseRelation.scala:145)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.createTable(HBaseRelation.scala:145)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:61)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource$.main(HBaseSource.scala:105)
	at org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource.main(HBaseSource.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by mcamendoza1** [comment]
To fix this bug create a Logging class. Base on spark docs:

[org.apache.spark.Logging](https://spark.apache.org/docs/1.6.3/api/java/org/apache/spark/Logging.html)
> NOTE: DO NOT USE this class outside of Spark. It is intended as an internal utility.  This will likely be changed or removed in future releases.
