### ISSUE TITLE
using SHC remote-hbase connection issue

### ISSUE THREAD

**Issue by srinivasugaddam** [hortonworks-spark/shc#216]
I have connected to local-hbase using SHC successfully.

--->Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x2dea42d10x0, quorum=localhost:2181, baseZNode=/hbase

But i faced several problems while connecting to remote hbase.

By reffering several documents, i came to know that we should place hbase-site.xml in 'spark-configuration' folder. so i placed hbase-site.xml. 

hbase-site.xml
----------------
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <property>
      <name>hbase.zookeeper.property.clientPort</name>
      <value>2181</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>xxxxxxx</value>
    </property>
    <property>
      <name>zookeeper.znode.parent</name>
      <value>/hbase</value>
    </property>
    <property>
      <name>hbase.cluster.distributed</name>
      <value>true</value>
    </property>
</configuration>

--->18/02/14 20:10:49 INFO ZooKeeper: Initiating client connection, connectString=xxxxxxx:2181 sessionTimeout=90000 watcher=hconnection-0x2dea42d10x0, quorum=xxxxxxx:2181 , baseZNode=/hbase
--->18/02/14 20:10:49 INFO ClientCnxn: Opening socket connection to server xxxxxxx/xxxxxxx:2181 . Will not attempt to authenticate using SASL (unknown error)
--->18/02/14 20:10:49 INFO ClientCnxn: Socket connection established to xxxxxxx/xxxxxxx:2181, initiating session
--->18/02/14 20:10:49 INFO ClientCnxn: Session establishment complete on server 10.1.7.24/10.1.7.24:2181, sessionid = 0x1616a01989b5a32, negotiated timeout = 60000

It is showing connectString=xxxxxxx/xxxxxxx:2181 ,but not able to write my df to hbase.

So by refering some of documents. I came to know that my zookeeper is searching for something else
I have edited my hosts file and placed 'xxxxxxx' in it.

so now it is able to create the table, but not able to load the data .
My log is as follows::

--->18/02/14 20:10:49 INFO ZooKeeper: Initiating client connection, connectString=xxxxxxx:2181 sessionTimeout=90000 watcher=hconnection-0x2dea42d10x0, quorum=xxxxxxx:2181, baseZNode=/hbase
18/02/14 20:10:49 INFO ClientCnxn: Opening socket connection to server xxxxxxx/xxxxxxx:2181. Will not attempt to authenticate using SASL (unknown error)
18/02/14 20:10:49 INFO ClientCnxn: Socket connection established to xxxxxxx/xxxxxxx:2181, initiating session
18/02/14 20:10:49 INFO ClientCnxn: Session establishment complete on server xxxxxxx/xxxxxxx:2181, sessionid = 0x1616a01989b5a32, negotiated timeout = 60000
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_1_piece0 on 10.1.10.XM:40295 in memory (size: 2.1 KB, free: 366.2 MB)
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_1_piece0 on slaveXS.msr.com:42570 in memory (size: 2.1 KB, free: 366.3 MB)
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_4_piece0 on 10.1.10.XM:40295 in memory (size: 42.0 KB, free: 366.3 MB)
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_4_piece0 on slaveXS.msr.com:36856 in memory (size: 42.0 KB, free: 366.3 MB)
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_5_piece0 on 10.1.10.XM:40295 in memory (size: 5.4 KB, free: 366.3 MB)
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_5_piece0 on slaveXS.msr.com:36856 in memory (size: 5.4 KB, free: 366.3 MB)
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 10.1.10.XM:40295 in memory (size: 30.6 KB, free: 366.3 MB)
18/02/14 20:10:51 INFO BlockManagerInfo: Removed broadcast_0_piece0 on slaveXS.msr.com:42570 in memory (size: 30.6 KB, free: 366.3 MB)
18/02/14 20:10:51 INFO ContextCleaner: Cleaned accumulator 98
18/02/14 20:10:51 INFO ContextCleaner: Cleaned accumulator 97
18/02/14 20:10:51 INFO ContextCleaner: Cleaned accumulator 99
-->18/02/14 20:10:56 INFO HBaseAdmin: Created Test_Table
18/02/14 20:10:56 INFO FileSourceStrategy: Pruning directories with:
18/02/14 20:10:56 INFO FileSourceStrategy: Post-Scan Filters:
18/02/14 20:10:56 INFO FileSourceStrategy: Output Data Schema: struct<serial_no: string, medallion: string, report_time: string, hack_license: string, vendor_id: string ... 13 more fields>
18/02/14 20:10:56 INFO FileSourceStrategy: Pushed Filters:
18/02/14 20:10:56 INFO MemoryStore: Block broadcast_6 stored as values in memory (estimated size 417.1 KB, free 365.9 MB)
18/02/14 20:10:56 INFO MemoryStore: Block broadcast_6_piece0 stored as bytes in memory (estimated size 42.0 KB, free 365.9 MB)
18/02/14 20:10:56 INFO BlockManagerInfo: Added broadcast_6_piece0 in memory on 10.1.10.212:40295 (size: 42.0 KB, free: 366.3 MB)
18/02/14 20:10:56 INFO SparkContext: Created broadcast 6 from save at NativeMethodAccessorImpl.java:0
18/02/14 20:10:56 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4194304 bytes, open cost is considered as scanning 4194304 bytes.
18/02/14 20:10:56 INFO SparkContext: Starting job: save at NativeMethodAccessorImpl.java:0
18/02/14 20:10:56 INFO DAGScheduler: Got job 3 (save at NativeMethodAccessorImpl.java:0) with 1 output partitions
18/02/14 20:10:56 INFO DAGScheduler: Final stage: ResultStage 3 (save at NativeMethodAccessorImpl.java:0)
18/02/14 20:10:56 INFO DAGScheduler: Parents of final stage: List()
18/02/14 20:10:56 INFO DAGScheduler: Missing parents: List()
18/02/14 20:10:56 INFO DAGScheduler: Submitting ResultStage 3 (MapPartitionsRDD[14] at save at NativeMethodAccessorImpl.java:0), which has no missing parents
18/02/14 20:10:57 INFO MemoryStore: Block broadcast_7 stored as values in memory (estimated size 215.0 KB, free 365.6 MB)
18/02/14 20:10:57 INFO MemoryStore: Block broadcast_7_piece0 stored as bytes in memory (estimated size 81.8 KB, free 365.6 MB)
18/02/14 20:10:57 INFO BlockManagerInfo: Added broadcast_7_piece0 in memory on 10.1.10.212:40295 (size: 81.8 KB, free: 366.2 MB)
18/02/14 20:10:57 INFO SparkContext: Created broadcast 7 from broadcast at DAGScheduler.scala:996
18/02/14 20:10:57 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 3 (MapPartitionsRDD[14] at save at NativeMethodAccessorImpl.java:0)
18/02/14 20:10:57 INFO YarnScheduler: Adding task set 3.0 with 1 tasks
18/02/14 20:10:57 INFO TaskSetManager: Starting task 0.0 in stage 3.0 (TID 3, slave214.msr.com, executor 2, partition 0, RACK_LOCAL, 6538 bytes)
18/02/14 20:10:57 INFO BlockManagerInfo: Added broadcast_7_piece0 in memory on slave214.msr.com:42570 (size: 81.8 KB, free: 366.2 MB)
18/02/14 20:10:59 INFO BlockManagerInfo: Added broadcast_6_piece0 in memory on slave214.msr.com:42570 (size: 42.0 KB, free: 366.2 MB)

The job is not terminated ,but still it is running for hours.

Job is not throwing any errors and exceptions.

And it is not loading the data into the created 'Test_Table'.

What might be the cause ?
 
Can anyone help me please.......

Thanking in advance...

**Comment by weiqingy** [comment]
It seems the application hung at "`BlockManagerInfo: Added broadcast_6_piece0 in memory on slave214.msr.com:4257`". Could you check if the spark application (aka. the application user) has the right to write data into hbase table? Did you try to create tables in hbase shell? Just want to confirm if your hbase worked correctly.

**Comment by srinivasugaddam** [comment]
Hi,
Let us consider two clusters A and B.

I am running my job in cluster B.

I want to load dataframe  to cluster A 's  hbase .

My HBase in cluster A is working fine. I have created a table and also kept data in it.

My cluster A's user is root.
My cluster B's user is test1.

I used by 'root' user of cluster A to create table in it. It worked fine.

And then i have granted test1 user of cluster B ,to  have 'RWXCA' permissions in cluster A
By using following command
--> grant 'test1', 'RWXCA'

Now my job in cluster B with username 'test1' is able to create table in cluster A's hbase.

how can i give permissions to the user 'test1' of cluster B to write data into table of cluster A's hbase

**Comment by weiqingy** [comment]
Just want to clarify. In HBase shell, could you write data into table of cluster A's hbase as the user 'test1' of cluster B?

**Comment by srinivasugaddam** [comment]
yes, i am able to write data into table of cluster A's hbase , using user 'test1' of Cluster B

**Comment by srinivasugaddam** [comment]
@weiqingy 
18/02/14 17:07:48 INFO ZooKeeper: Initiating client connection, connectString=10.1.7.74:2181 sessionTimeout=90000 watcher=hconnection-0x72f7bfdf0x0, quorum=10.1.7.74:2181, baseZNode=/hbase
18/02/14 17:07:48 INFO ClientCnxn: Opening socket connection to server 10.1.7.74/10.1.7.74:2181. Will not attempt to authenticate using SASL (unknown error)
18/02/14 17:07:48 INFO ClientCnxn: Socket connection established to 10.1.7.74/10.1.7.74:2181, initiating session
18/02/14 17:07:48 INFO ClientCnxn: Session establishment complete on server 10.1.7.74/10.1.7.74:2181, sessionid = 0x1611b8e22980194, negotiated timeout = 40000
18/02/14 17:07:48 INFO TableOutputFormat: Created table instance for default:10trip_test
18/02/14 17:07:48 INFO FileScanRDD: Reading File path: hdfs://10.1.7.24:8020/lekya/tripdata_sample.csv, range: 0-640, partition values: [empty row]
18/02/14 17:07:48 INFO CodeGenerator: Code generated in 39.177424 ms
18/02/14 17:07:48 INFO TorrentBroadcast: Started reading broadcast variable 6
18/02/14 17:07:48 INFO MemoryStore: Block broadcast_6_piece0 stored as bytes in memory (estimated size 42.0 KB, free 366.0 MB)
18/02/14 17:07:48 INFO TorrentBroadcast: Reading broadcast variable 6 took 34 ms
18/02/14 17:07:48 INFO MemoryStore: Block broadcast_6 stored as values in memory (estimated size 508.8 KB, free 365.5 MB)
18/02/14 17:44:41 ERROR AsyncProcess: Failed to get region location 
org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 14 17:44:41 IST 2018, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68685: row '10trip_test,1,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=sandbox.hortonworks.com,16020,1518603386098, seqNum=0

	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.throwEnrichedException(RpcRetryingCallerWithReadReplicas.java:271)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:195)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:59)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
	at org.apache.hadoop.hbase.client.ClientSmallReversedScanner.loadCache(ClientSmallReversedScanner.java:211)
	at org.apache.hadoop.hbase.client.ClientSmallReversedScanner.next(ClientSmallReversedScanner.java:185)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1249)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1155)
	at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:370)
	at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:321)
	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:206)
	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.close(BufferedMutatorImpl.java:158)
	at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:111)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$5.apply$mcV$sp(PairRDDFunctions.scala:1131)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1359)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1131)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=68685: row '10trip_test,1,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=sandbox.hortonworks.com,16020,1518603386098, seqNum=0
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:159)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:64)
	... 3 more
Caused by: java.net.UnknownHostException: unknown host: sandbox.hortonworks.com
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.<init>(RpcClientImpl.java:316)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.createConnection(RpcClientImpl.java:130)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.getConnection(RpcClientImpl.java:1326)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1204)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:213)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:287)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:32831)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:201)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:180)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:346)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:320)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
	... 4 more



This might be the problem.

What can i do to slove this??

**Comment by srinivasugaddam** [comment]
Actually i am used master as yarn-client. The problem is due to my yarn resources problem.

I changed my master to local and performed the job.It has been executed successfully.
