### ISSUE TITLE
Field "col0" does not exist

### ISSUE THREAD

**Issue by sunny1978** [hortonworks-spark/shc#217]
Error: java.lang.IllegalArgumentException: Field "col0" does not exist.

<dependency>
		<groupId>com.hortonworks</groupId>
		<artifactId>shc-core</artifactId>
		<version>1.1.0-2.1-s_2.11</version>
</dependency>
HDP 2.6 Cluster - Hortonworks.  (2.6.0.3-8)

Looks like I did not understand mechanics behind creating catalog. For my table - what is the right catalog? 

Approach:1 "col0"
============
Stack:
java.lang.IllegalArgumentException: Field "col0" does not exist.
        at org.apache.spark.sql.types.StructType$$anonfun$fieldIndex$1.apply(StructType.scala:290)
        at org.apache.spark.sql.types.StructType$$anonfun$fieldIndex$1.apply(StructType.scala:290)
        at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
        at scala.collection.AbstractMap.getOrElse(Map.scala:59)
        at org.apache.spark.sql.types.StructType.fieldIndex(StructType.scala:289)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$9.apply(HBaseRelation.scala:177)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$9.apply(HBaseRelation.scala:176)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.insert(HBaseRelation.scala:176)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:61)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:518)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)

Logs:
===============
Data Frame -Schema
18/02/21 17:52:03 INFO HBaseSink: executeBatch::rddDF:[qualifier: string, rowKey: string ... 2 more fields]
root
 |-- qualifier: string (nullable = true)
 |-- rowKey: string (nullable = true)
 |-- uniqueId: string (nullable = true)
 |-- value: long (nullable = false)

18/02/21 17:52:03 INFO HBaseSink: getCatalog::**Table**:CHANNEL_METRICS.RAW_METRICS_COPY;hconnection-0x5b540faf
18/02/21 17:52:04 INFO HBaseSink: getCatalog::**cfdesc**:{NAME => 'cf', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0', VERSIONS => '1', COMPRESSION => 'NONE', MIN_VERSIONS => '0', TTL => 'FOREVER', KEEP_DELETED_CELLS => 'FALSE', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}

18/02/21 17:52:04 INFO HBaseSink: **getCatalog**::{"table":{"namespace":"CHANNEL_METRICS","name":"RAW_METRICS_COPY"},"rowkey":"key","columns":{"**col0**":{"cf":"rowkey", "col":"key","type":"string"},"GGAR::NTR::EUS-BT::MTR-BKT":{"cf":"cf", "col":"GGAR::NTR::EUS-BT::MTR-BKT","type":"binary"}}}

18/02/21 17:52:04 INFO HBaseSink: **getOptions**::{catalog={"table":{"namespace":"CHANNEL_METRICS","name":"RAW_METRICS_COPY"},"rowkey":"key","columns":{"col0":{"cf":"rowkey", "col":"key","type":"string"},"GGAR::NTR::EUS-BT::MTR-BKT":{"cf":"cf", "col":"GGAR::NTR::EUS-BT::MTR-BKT","type":"binary"}}}}

18/02/21 17:52:04 ERROR GiniBase: executeWorkflowBatch::Exception while processing sink.config{HBaseSinkConfig: {type :hbase, confFilePath :/etc/hbase/conf/hbase-site.xml, schemaName :CHANNEL_METRICS, tableName :RAW_METRICS_COPY, rowKey :null, columnFamily :cf, columnNameTypes :GGAR::NTR::EUS-BT::MTR-BKT$binary, objectType :com.ihg.gini.dto.RawMetrics, zNodeParent :null, zkQuorum :null}}, object:com.ihg.gini.sink.HBaseSink@1d7eb901
java.lang.IllegalArgumentException: Field "col0" does not exist.

My Table Info:
==================
hbase(main):001:0> scan 'CHANNEL_METRICS.RAW_METRICS',{LIMIT => 1}
ROW                                        COLUMN+CELL
201801240950-201801240959                 column=cf:GGAR::CHN-UNKNH::EUS-BT::MTR-BKT, timestamp=1516831569530, value=\x00\x00\x00\x00\x00\x00\x00:
201801240950-201801240959                 column=cf:GGAR::NTR::EUS-BT::MTR-BKT, timestamp=1516831569527, value=\x00\x00\x00\x00\x00\x00\x00:
201801240950-201801240959                 column=cf:GGAR::NTT50::EUS-BT::MTR-BKT, timestamp=1516831569517, value=\x00\x00\x00\x00\x00\x00\x00;
201801240950-201801240959                 column=cf:GGAR::PID-L05::EUS-BT::MTR-BKT, timestamp=1516831569507, value=\x00\x00\x00\x00\x00\x00\x00:
201801240950-201801240959                 column=cf:GGAR::REG-1::EUS-BT::MTR-BKT, timestamp=1516831569519, value=\x00\x00\x00\x00\x00\x00\x00:
1 row(s) in 0.7110 seconds

hbase(main):003:0* get 'CHANNEL_METRICS.RAW_METRICS','201801240950-201801240959'
COLUMN                                     CELL
cf:GGAR::CHN-UNKNH::EUS-BT::MTR-BKT       timestamp=1516831569530, value=\x00\x00\x00\x00\x00\x00\x00:
cf:GGAR::NTR::EUS-BT::MTR-BKT             timestamp=1516831569527, value=\x00\x00\x00\x00\x00\x00\x00:
cf:GGAR::NTT50::EUS-BT::MTR-BKT           timestamp=1516831569517, value=\x00\x00\x00\x00\x00\x00\x00;
cf:GGAR::PID-L05::EUS-BT::MTR-BKT         timestamp=1516831569507, value=\x00\x00\x00\x00\x00\x00\x00:
cf:GGAR::REG-1::EUS-BT::MTR-BKT           timestamp=1516831569519, value=\x00\x00\x00\x00\x00\x00\x00:
5 row(s) in 0.0890 seconds

==========================

**Comment by sunny1978** [comment]
For above table & dataframe: I tried this catalog.
{
	"table":{"namespace":"CHANNEL_METRICS","name":"RAW_METRICS_COPY"},
	"rowkey":"rowkey",
	"columns":{
		"rowKey":{"cf":"rowkey", "col":"key","type":"string"},
		"GGAR::NTR::EUS-BT::MTR-BKT":{"cf":"cf", "col":"GGAR::NTR::EUS-BT::MTR-BKT","type":"binary"}
	}
}

Result: 
18/02/21 18:23:35 ERROR GiniBase: executeWorkflowBatch::Exception while processing sink.config{HBaseSinkConfig: {type :hbase, confFilePath :/etc/hbase/conf/hbase-site.
xml, schemaName :CHANNEL_METRICS, tableName :RAW_METRICS_COPY, rowKey :rowKey, columnFamily :cf, columnNameTypes :GGAR::NTR::EUS-BT::MTR-BKT$binary, objectType :com.ih
g.gini.dto.RawMetrics, zNodeParent :null, zkQuorum :null}}, object:com.ihg.gini.sink.HBaseSink@60d4e3e7
java.lang.UnsupportedOperationException: empty.tail
        at scala.collection.TraversableLike$class.tail(TraversableLike.scala:421)
        at scala.collection.mutable.ArraySeq.scala$collection$IndexedSeqOptimized$$super$tail(ArraySeq.scala:46)
        at scala.collection.IndexedSeqOptimized$class.tail(IndexedSeqOptimized.scala:129)
        at scala.collection.mutable.ArraySeq.tail(ArraySeq.scala:46)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog.initRowKey(HBaseTableCatalog.scala:185)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog.<init>(HBaseTableCatalog.scala:199)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$.apply(HBaseTableCatalog.scala:293)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:77)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:59)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:518)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)

**Comment by sunny1978** [comment]
Take2: Only rowkey and no extra columns
{
"table":{"namespace":"CHANNEL_METRICS","name":"RAW_METRICS_COPY"},
"rowkey":"key",
"columns":{"rowKey":{"cf":"rowkey", "col":"key","type":"string"}}
}

18/02/21 18:41:54 ERROR GiniBase: executeWorkflowBatch::Exception while processing sink.config{HBaseSinkConfig: {type :hbase, confFilePath :/etc/hbase/conf/hbase-site.
xml, schemaName :CHANNEL_METRICS, tableName :RAW_METRICS_COPY, rowKey :rowKey, columnFamily :cf, columnNameTypes :null, objectType :com.ihg.gini.dto.RawMetrics, zNodeP
arent :null, zkQuorum :null}}, object:com.ihg.gini.sink.HBaseSink@7498896c
java.util.NoSuchElementException: key not found: qualifier
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at org.apache.spark.sql.execution.datasources.hbase.SchemaMap.getField(HBaseTableCatalog.scala:156)

**Comment by sunny1978** [comment]
Take3: With a column qualifier
{
"table":{"namespace":"CHANNEL_METRICS","name":"RAW_METRICS_COPY"},
"rowkey":"key",
"columns":{
	"rowKey":{"cf":"rowkey", "col":"key","type":"string"},
	"GGAR::NTR::EUS-BT::MTR-BKT":{"cf":"cf", "col":"GGAR::NTR::EUS-BT::MTR-BKT","type":"binary"}
	}
}

18/02/21 18:44:29 ERROR GiniBase: executeWorkflowBatch::Exception while processing sink.config{HBaseSinkConfig: {type :hbase, confFilePath :/etc/hbase/conf/hbase-site.
xml, schemaName :CHANNEL_METRICS, tableName :RAW_METRICS_COPY, rowKey :rowKey, columnFamily :cf, columnNameTypes :GGAR::NTR::EUS-BT::MTR-BKT$binary, objectType :com.ih
g.gini.dto.RawMetrics, zNodeParent :null, zkQuorum :null}}, object:com.ihg.gini.sink.HBaseSink@305e2149
java.util.NoSuchElementException: key not found: qualifier
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at org.apache.spark.sql.execution.datasources.hbase.SchemaMap.getField(HBaseTableCatalog.scala:156)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog.getField(HBaseTableCatalog.scala:169)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$11.apply(HBaseRelation.scala:182)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$11.apply(HBaseRelation.scala:182)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.insert(HBaseRelation.scala:182)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:61)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:518)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)

**Comment by sunny1978** [comment]
Hi @weiqingy could you please look in to this issue and help me.

**Comment by weiqingy** [comment]
Hi @sunny1978 

Which SHC version you were using? Are there 'null's in your data? 

Just want to confirm with you:
Is this the schema of the Data Frame which you want to save into a new Hbase table? Or is the hbase table a existing table?

root
|-- qualifier: string (nullable = true)
|-- rowKey: string (nullable = true)
|-- uniqueId: string (nullable = true)
|-- value: long (nullable = false)

If the dataframe has 4 field, why there is only one column in the hbase table?
"GGAR::NTR::EUS-BT::MTR-BKT":{"cf":"cf", "col":"GGAR::NTR::EUS-BT::MTR-BKT","type":"binary"

**Comment by sunny1978** [comment]
1 SHC Version:
<dependency>
   <groupId>com.hortonworks</groupId>
   <artifactId>shc-core</artifactId>
   <version>1.1.0-2.1-s_2.11</version>
  </dependency>

2: HDP Version: 2.6.0.3-8 Hortonworks

3: NULLS: I am not expecting any.

4: Yes HTable destination exists. Its schema:
hbase(main):002:0> desc 'CHANNEL_METRICS.RAW_METRICS_COPY'
Table CHANNEL_METRICS.RAW_METRICS_COPY is ENABLED
CHANNEL_METRICS.RAW_METRICS_COPY
COLUMN FAMILIES DESCRIPTION
{NAME => 'cf', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW',
REPLICATION_SCOPE => '0', VERSIONS => '1', COMPRESSION => 'NONE',
MIN_VERSIONS => '0', TTL => 'FORE
VER', KEEP_DELETED_CELLS => 'FALSE', BLOCKSIZE => '65536', IN_MEMORY =>
'false', BLOCKCACHE => 'true'}


5: Yes dataframe:
root
|-- qualifier: string (nullable = true) (my counter name: ex:
GGAR::NTR::EUS-BT::MTR-BKT
|-- rowKey: string (nullable = true)
|-- uniqueId: string (nullable = true) ---> This is not existing in the
Hbase table. It is something unwanted and showing up. Is this causing the
issue?
|-- value: long (nullable = false) (my counter value. Ex: 1)

Background:
This hbase table is a counter table. I am having one row-key and qualifier
as counter names and value is some long.
I have about 10 counter-name. Now all exists for a given rowKey. If we have
a qualifier, value always exists. Defaults to 1

**Comment by sunny1978** [comment]
I recompiled and removed unwanted uniqueId
Logs:

18/02/22 17:21:00 INFO HBaseSink: executeBatch::rddDF:[qualifier: string, rowKey: string ... 1 more field]
root
 |-- qualifier: string (nullable = true)
 |-- rowKey: string (nullable = true)
 |-- value: long (nullable = false)

+--------------------+--------------------+-----+
|           qualifier|              rowKey|value|
+--------------------+--------------------+-----+
|GGAR::CHN-UNKNH::...|201801240950-2018...|   58|
|GGAR::NTR::EUS-BT...|201801240950-2018...|   58|

18/02/22 17:21:05 INFO HBaseSink: getCatalog::Table:CHANNEL_METRICS.RAW_METRICS_COPY;hconnection-0x784cb6e7
18/02/22 17:21:05 INFO HBaseSink: getCatalog::cfdesc:{NAME => 'cf', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0', VERSIONS => '1', COMPRESSION => 'NONE', MIN_VERSIONS => '0', TTL => 'FOREVER', KEEP_DELETED_CELLS => 'FALSE', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}
18/02/22 17:21:05 INFO HBaseSink: getCatalog::{"table":{"namespace":"CHANNEL_METRICS","name":"RAW_METRICS_COPY"},"rowkey":"key","columns":{"col0":{"cf":"rowkey", "col":"key","type":"string"},"GGAR::NTR::EUS-BT::MTR-BKT":{"cf":"cf", "col":"GGAR::NTR::EUS-BT::MTR-BKT","type":"binary"}}}
18/02/22 17:21:05 INFO HBaseSink: getOptions::{catalog={"table":{"namespace":"CHANNEL_METRICS","name":"RAW_METRICS_COPY"},"rowkey":"key","columns":{"col0":{"cf":"rowkey", "col":"key","type":"string"},"GGAR::NTR::EUS-BT::MTR-BKT":{"cf":"cf", "col":"GGAR::NTR::EUS-BT::MTR-BKT","type":"binary"}}}}
18/02/22 17:21:06 ERROR GiniBase: executeWorkflowBatch::Exception while processing sink.config{HBaseSinkConfig: {type :hbase, confFilePath :/etc/hbase/conf/hbase-site.xml, schemaName :CHANNEL_METRICS, tableName :RAW_METRICS_COPY, rowKey :col0, columnFamily :cf, columnNameTypes :GGAR::NTR::EUS-BT::MTR-BKT$binary, objectType :com.ihg.gini.dto.RawMetrics, zNodeParent :null, zkQuorum :null, mode :bulk}}, object:com.ihg.gini.sink.HBaseSink@87f70e4
java.lang.IllegalArgumentException: Field "col0" does not exist.
        at org.apache.spark.sql.types.StructType$$anonfun$fieldIndex$1.apply(StructType.scala:290)
        at org.apache.spark.sql.types.StructType$$anonfun$fieldIndex$1.apply(StructType.scala:290)
        at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
        at scala.collection.AbstractMap.getOrElse(Map.scala:59)
        at org.apache.spark.sql.types.StructType.fieldIndex(StructType.scala:289)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$9.apply(HBaseRelation.scala:177)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$9.apply(HBaseRelation.scala:176)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.insert(HBaseRelation.scala:176)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:61)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:518)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)

**Comment by sunny1978** [comment]
I entered all the fields now. It looks like accepted and moved little further. 
My Data Frame:
============
root
 |-- qualifier: string (nullable = true)
 |-- rowKey: string (nullable = true)
 |-- value: long (nullable = false)

My Table:
==========
hbase(main):002:0> desc 'CHANNEL_METRICS.RAW_METRICS_COPY'
Table CHANNEL_METRICS.RAW_METRICS_COPY is ENABLED
CHANNEL_METRICS.RAW_METRICS_COPY
COLUMN FAMILIES DESCRIPTION
{NAME => 'cf', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW',
REPLICATION_SCOPE => '0', VERSIONS => '1', COMPRESSION => 'NONE',
MIN_VERSIONS => '0', TTL => 'FORE
VER', KEEP_DELETED_CELLS => 'FALSE', BLOCKSIZE => '65536', IN_MEMORY =>
'false', BLOCKCACHE => 'true'}

My Catalog
============

{"table":{"**namespace**":"CHANNEL_METRICS","**name**":"RAW_METRICS_COPY"},
"rowkey":"key",
"columns":{
"rowKey":{"cf":"rowkey", "col":"key","type":"string"},
"qualifier":{"cf":"cf", "col":"qualifier","type":"binary"},
"value":{"cf":"cf", "col":"value","type":"binary"}}}

Logs
==========
18/02/22 17:30:40 ERROR GiniBase: executeWorkflowBatch::Exception while processing sink.config{HBaseSinkConfig: {type :hbase, confFilePath :/etc/hbase/conf/hbase-site.
xml, schemaName :CHANNEL_METRICS, tableName :RAW_METRICS_COPY, rowKey :rowKey, columnFamily :cf, columnNameTypes :qualifier$binary,value$binary, objectType :com.ihg.gi
ni.dto.RawMetrics, zNodeParent :null, zkQuorum :null, mode :bulk}}, object:com.ihg.gini.sink.HBaseSink@5f47a0aa
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 5, mksd1dll
lyin009.c.iron-potion-771.internal, executor 5): org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 3159 actions: Table 'RAW_METRICS_COPY' was
 not found, got: MESSAGE_LOGS_ST2.IF_MESSAGE.: 3159 times,

I gave name space in the catalog, why it did not accept it?

**Comment by weiqingy** [comment]
In Hbase master UI, could you check the table name? Is it all upper letters?

**Comment by sunny1978** [comment]
List shows all caps
hbase(main):001:0> !list
TABLE
CHANNEL_METRICS.RAW_METRICS_COPY -----> this is my destination
CHANNEL_METRICS.RAW_METRICS ----> this is my source

**Comment by sunny1978** [comment]
This Catalog FINALLY WORKED

{"table":{"namespace":"CHANNEL_METRICS","name":"CHANNEL_METRICS.RAW_METRICS_COPY"},
"rowkey":"key",
"columns":{
"rowKey":{"cf":"rowkey", "col":"key","type":"string"},
"qualifier":{"cf":"cf", "col":"qualifier","type":"binary"},
"value":{"cf":"cf", "col":"value","type":"binary"}}}

Wow - it took 5 seconds to copy Hbase to Hbase using SHC.

Destination:
hbase(main):002:0> count 'CHANNEL_METRICS.RAW_METRICS_COPY'
Current count: 1000, row: 201802070700-201802070709
Current count: 2000, row: 201802161430-201802161439
2810 row(s) in 1.5100 seconds


Source Table:
hbase(main):003:0> count 'CHANNEL_METRICS.RAW_METRICS'
Current count: 1000, row: 201802070700-201802070709
Current count: 2000, row: 201802161430-201802161439
2810 row(s) in 0.7140 seconds

Non SHC Approach: Bulk Puts: It took 25 mins. for same table.

**Comment by sunny1978** [comment]
@weiqingy  Thank you for your suppor.

**Comment by sunny1978** [comment]
Using this in JAVA
1: Maven repo and dependency
<repository>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
				<checksumPolicy>warn</checksumPolicy>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
				<checksumPolicy>fail</checksumPolicy>
			</snapshots>
			<id>HDPReleases</id>
			<name>HDP Releases</name>
			
			<url>http://repo.hortonworks.com/content/groups/public/</url>
			<layout>default</layout>
		</repository>

<dependency>
			<groupId>com.hortonworks</groupId>
			<artifactId>shc-core</artifactId>
			<version>1.1.0-2.1-s_2.11</version>
		</dependency>

2: POJO: that matches and include rowKey, qualifier and all columns related to that qualifier.
Stick to one pojo for each qualifier
public class RawMetrics implements Serializable
private String rowKey;
 private String qualifier;
private long value;
getters & setters

3: pick dataframe, catalog etc from above threads
