### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration

### ISSUE THREAD

**Issue by devGichanLee** [hortonworks-spark/shc#223]
Trackback
```
File "DFsave.py", line 27, in <module>
    df.write.options(catalog=catalog,newTable="4").format(data_source_format).save()
  File "/home/keti/opt_keti/hadoop/tmp/nm-local-dir/usercache/keti/appcache/application_1521096436352_0002/container_1521096436352_0002_02_000001/pyspark.zip/pyspark/sql/readwriter.py", line 701, in save
  File "/home/keti/opt_keti/hadoop/tmp/nm-local-dir/usercache/keti/appcache/application_1521096436352_0002/container_1521096436352_0002_02_000001/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
  File "/home/keti/opt_keti/hadoop/tmp/nm-local-dir/usercache/keti/appcache/application_1521096436352_0002/container_1521096436352_0002_02_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/home/keti/opt_keti/hadoop/tmp/nm-local-dir/usercache/keti/appcache/application_1521096436352_0002/container_1521096436352_0002_02_000001/py4j-0.10.6-src.zip/py4j/protocol.py", line 320, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o64.save.
: java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:108)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:63)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:654)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.HBaseConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

2018-03-15 00:34:47 ERROR ApplicationMaster:70 - User application exited with status 1
```
Code(DFsave.py)
```
from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.conf import SparkConf

conf = SparkConf().set('spark.yarn.dist.files', 'hdfs:/spark/workerlib/py4j-0.10.6-src.zip,hdfs:/spark/workerlib/pyspark.zip')
conf.setExecutorEnv('PYTHONPATH', 'pyspark.zip:py4j-0.10.6-src.zip')
conf.setMaster('yarn')
sc = SparkContext(conf=conf)
sqlc = SQLContext(sc)

data_source_format = 'org.apache.spark.sql.execution.datasources.hbase'

df = sc.parallelize([('a', '1.0'), ('b', '2.0')]).toDF(schema=['col0', 'col1'])

# ''.join(string.split()) in order to write a multi-line JSON string here.
catalog = ''.join("""{
    "table":{"namespace":"default", "name":"testtable"},
    "rowkey":"key",
    "columns":{
        "col0":{"cf":"rowkey", "col":"key", "type":"string"},
        "col1":{"cf":"cf", "col":"col1", "type":"string"}
    }
}""".split())


# Writing
df.write.options(catalog=catalog,newTable="4").format(data_source_format).save()

```
Command
`spark-submit --master yarn --deploy-mode cluster --jars ~/opt_keti/shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar --files hdfs:///spark/workerlib/hbase-site.xml DFsave.py`

Hadoop-env.sh
```
...
export HADOOP_CLASSPATH="$HADOOP_CLASSPATH:$HBASE_HOME/lib/*"
...
```

Hello, I'm newbie of shc. I'm struggle to write a dataframe to HBase from Spark now.
Could I get some helps from this community? I'm using these items.

```
Spark 2.3.0-Hadoop 2.7.4 (from Spark 2.2.0 because of #191
HBase 1.2.6
shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar
```

I also read some threads that related to this issue like #69 but It wasn't helpful unfortunately.
I tried changing Hbase version to 1.2.6 of 'pom.xml' in shc repo, hadoop-env.sh in all nodes, and etc.
ah, also checked the existence of the HBaseConfiguration.class in shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar, It wasn't found it. and I did mvn package in shc not in shc/core.

I respect you guys for making truly good connector. thanks in advance.
help me plz T^T

**Comment by ser0t0nin** [comment]
Hello! I have the same problem with HDP 2.6.3 stack and the same pyspark code
Spark 2.2.0
Hbase 1.1.2
shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar built manually from sources (did not find it in http://repo.hortonworks.com/content/repositories/releases/com/hortonworks/shc/)

**Comment by weiqingy** [comment]
@ser0t0nin Does building manually the SHC source code https://github.com/hortonworks-spark/shc/tree/branch-2.2 resolve the issues?

**Comment by devGichanLee** [comment]
@weiqingy I did it manually to get shc-core-1.1.2-2.2 which isn't found on the repo of hortonworks. and the problem occurs as I said.

**Comment by ser0t0nin** [comment]
@weiqingy no it did not.
My pyspark code is as follows:
`data_source_format = 'org.apache.spark.sql.execution.datasources.hbase'

df = sc.parallelize([('a', '1.0'), ('b', '2.0')]).toDF(schema=['col0', 'col1'])

# ''.join(string.split()) in order to write a multi-line JSON string here.
catalog = ''.join("""{
    "table":{"namespace":"default", "name":"testtable"},
    "rowkey":"key",
    "columns":{
        "col0":{"cf":"rowkey", "col":"key", "type":"string"},
        "col1":{"cf":"cf", "col":"col1", "type":"string"}
    }
}""".split())


# Writing
df.write\
.options(catalog=catalog)\
.format(data_source_format)\
.save()
print 'done'
# Reading
df_ = sqlc.read\
.options(catalog=catalog)\
.format(data_source_format)\
.load()

df_.show()`

I provide the shc-core jar, built from sources of branch-2.2 (from your link) as follows:
`hdfs://hdp-master:8020/jars/shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar`

The error is like this:
`Py4JJavaError: An error occurred while calling o133.save.
: java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:108)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:63)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:471)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
<...>`

**Comment by weiqingy** [comment]
If you want to use the jars published by Hortonworks, you may need to download the jars from another repo http://nexus-private.hortonworks.com/nexus/content/groups/public/. Please refer to the discussion thread https://github.com/hortonworks-spark/shc/issues/225 for more information.

If you use the jar you manually build from sources of branch-2.2, then you also need to provide the hbase jars, e.g.:
```
spark-submit --verbose --class org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource --master yarn-client --jars  shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar,/usr/hdp/current/hbase-client/lib/htrace-core-3.1.0-incubating.jar,/usr/hdp/current/hbase-client/lib/hbase-client.jar,/usr/hdp/current/hbase-client/lib/hbase-common.jar,/usr/hdp/current/hbase-client/lib/hbase-server.jar,/usr/hdp/current/hbase-client/lib/guava-12.0.1.jar,/usr/hdp/current/hbase-client/lib/hbase-protocol.jar,/usr/hdp/current/hbase-client/lib/htrace-core-3.1.0-incubating.jar --files /usr/hdp/current/hbase-client/conf/hbase-site.xml  shc-examples.jar
```

**Comment by devGichanLee** [comment]
@weiqingy Thank you so much but the shc 1.1.2-2.2-s_2.11

**Comment by devGichanLee** [comment]
@weiqingy I finally got success from this package
`spark-submit --master yarn --deploy-mode cluster --packages com.hortonworks.shc:shc-core:1.1.0.2.6.5.2-8 --repositories http://nexus-private.hortonworks.com/nexus/content/groups/public --files hdfs:///spark/workerlib/hbase-site.xml DFsave.py `
but as you can see, It's not shc 1.1.2-2.2 which is fixed version for SPARK-21549, but actually it works.
I can't find what was problem in my case now.

**Comment by ser0t0nin** [comment]
@weiqingy that worked for me, thank you! Probably you should add this trait to the docs, because HBase package has a lot of jars in the lib/ and it is difficult to find necessary ones

**Comment by omkarahane** [comment]
> (1) If you want to use the jars published by Hortonworks, you may need to download the jars from another repo http://nexus-private.hortonworks.com/nexus/content/groups/public/. Please refer to the discussion thread #225 for more information.
> 
> (2) If you use the jar you manually build from sources of branch-2.2, then you also need to provide the hbase jars, e.g.:
> 
> ```
> spark-submit --verbose --class org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource --master yarn-client --jars  shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar,/usr/hdp/current/hbase-client/lib/htrace-core-3.1.0-incubating.jar,/usr/hdp/current/hbase-client/lib/hbase-client.jar,/usr/hdp/current/hbase-client/lib/hbase-common.jar,/usr/hdp/current/hbase-client/lib/hbase-server.jar,/usr/hdp/current/hbase-client/lib/guava-12.0.1.jar,/usr/hdp/current/hbase-client/lib/hbase-protocol.jar,/usr/hdp/current/hbase-client/lib/htrace-core-3.1.0-incubating.jar --files /usr/hdp/current/hbase-client/conf/hbase-site.xml  shc-examples.jar
> ```

Hi @weiqingy , This comment helped me a lot, was facing error using SHC, I have uploaded all the jars you mentioned and the main error I was facing has been resolved but I'm facing another error,
```
java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
```
This also seems to be a dependency issue, This is what I have tried,
1. Uploaded the following jars: json4s-ast, json4s-core,json4s-jackson
2. Versions tried, 3.4,3.5,3.6
3. Put a maven dependency in my jar, built fat jar and uploaded it as library, so transitive dependencies can be satisfied.

Still getting the same error. Can you please help.

**Comment by moonyouj889** [comment]
> > (1) If you want to use the jars published by Hortonworks, you may need to download the jars from another repo http://nexus-private.hortonworks.com/nexus/content/groups/public/. Please refer to the discussion thread #225 for more information.
> > (2) If you use the jar you manually build from sources of branch-2.2, then you also need to provide the hbase jars, e.g.:
> > ```
> > spark-submit --verbose --class org.apache.spark.sql.execution.datasources.hbase.examples.HBaseSource --master yarn-client --jars  shc-core-1.1.2-2.2-s_2.11-SNAPSHOT.jar,/usr/hdp/current/hbase-client/lib/htrace-core-3.1.0-incubating.jar,/usr/hdp/current/hbase-client/lib/hbase-client.jar,/usr/hdp/current/hbase-client/lib/hbase-common.jar,/usr/hdp/current/hbase-client/lib/hbase-server.jar,/usr/hdp/current/hbase-client/lib/guava-12.0.1.jar,/usr/hdp/current/hbase-client/lib/hbase-protocol.jar,/usr/hdp/current/hbase-client/lib/htrace-core-3.1.0-incubating.jar --files /usr/hdp/current/hbase-client/conf/hbase-site.xml  shc-examples.jar
> > ```
> 
> Hi @weiqingy , This comment helped me a lot, was facing error using SHC, I have uploaded all the jars you mentioned and the main error I was facing has been resolved but I'm facing another error,
> 
> ```
> java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
> ```
> 
> This also seems to be a dependency issue, This is what I have tried,
> 
> 1. Uploaded the following jars: json4s-ast, json4s-core,json4s-jackson
> 2. Versions tried, 3.4,3.5,3.6
> 3. Put a maven dependency in my jar, built fat jar and uploaded it as library, so transitive dependencies can be satisfied.
> 
> Still getting the same error. Can you please help.

Hi @omkarahane. I had the same issue with spark 2.4, and I digged around the internet to finally make it work.

I referred to https://github.com/dhananjaypatkar/shc cloned locally and built the package. The pom file is missing hbase-client, so make sure to add that in with version 3.0.0-SNAPSHOT. Then I added the jar file created from the build to the list of jar files as mentioned by weiqingy.

Hope this helps.
