### ISSUE TITLE
Issue with Kerberos when running from local machine

### ISSUE THREAD

**Issue by rakesh-kanchalwar** [hortonworks-spark/shc#242]
I am working on hbase with spark for which I am using shc connector. I am able to execute the code with spark-submit on Hadoop cluster.
But when I am running the job from my local machine, it is failing for Kerberos. I read that we need to configure the SPARK_CONF_DIR and below configurations,
  
spark.hbase.connector.security.credentials.enabled true
spark.hbase.connector.security.credentials  ambari-qa-c1@EXAMPLE.COM
spark.hbase.connector.security.keytab  /etc/security/keytabs/smokeuser.headless.keytab
I am bit confused about where to configure these parameters when I am running spark job from local (hbase is installed on in premise cluster).
I tried using UserGroupConfiguration but it fails with “Unable to obtain password from user”. After debugging, What I found is that it is not able to find a token for a service.

Here is stacktrace for the same,
 
at org.apache.hadoop.security.UserGroupInformation.loginUserFromKeytabAndReturnUGI(UserGroupInformation.java:1146)
                at org.apache.spark.sql.execution.datasources.hbase.SHCCredentialsManager.org$apache$spark$sql$execution$datasources$hbase$SHCCredentialsManager$$getNewToken(SHCCredentialsManager.scala:189)
                at org.apache.spark.sql.execution.datasources.hbase.SHCCredentialsManager.getTokenForCluster(SHCCredentialsManager.scala:122)

Is there any other way where we can configure the required parameters in the connector?

**Comment by zoran1996** [comment]
Have you figured out how to set thoes parameters or you find someway else that solved that problems?
if you have,please answer me，i am in hurry ，thankssssss!
