### ISSUE TITLE
Issue with avro Table coder for writing dataframe to  hbase 

### ISSUE THREAD

**Issue by vineelavelagapudi** [hortonworks-spark/shc#267]

**Comment by vineelavelagapudi** [comment]
avroschema = ("""{"namespace": "default","type": "record","name": "user",
"fields": [
{"name:serial_no", "type":"string"},
{"name:medallion", "type":"string"},
{"name:report_time", "type":"string"},
{"name:hack_license", "type":"string"},
{"name:vendor_id", "type":"string"},
{"name:rate_code", "type":"string"},
{"name:store_and_fwd_flag", "type":"string"},
{"name:pickup_datetime", "type":"string"},
{"name:dropoff_datetime", "type":"string"},
{"name:passenger_count", "type":"string"},
{"name:trip_time_in_secs", "type":"string"},
{"name:trip_distance", "type":"string"},
{"name:pickup_longitude", "type":"string"},
{"name:pickup_latitude", "type":"string"},
{"name:dropoff_longitude", "type":"string"},
{"name:dropoff_latitude", "type":"string"}
]
}""")



hbaseschema2 = {
"table": {"namespace": "default","name": "trip_avro","tableCoder":"avro"},
"rowkey": "key1",
"columns": {
		"col1": {"cf": "rowkey","col": "key1","type": "int"},
		"col2": {"cf": "sales","col": "col2","type": "string", "avro":"avroschema"},
		}
}



import json

cat2=json.dumps(hbaseschema2)

from pyspark.sql.functions import col

for i in df3.columns:
        df3= df3.withColumn(i, col(i).cast("string"))


df3.write.option("catalog",cat2).option("newtable","5").format("org.apache.spark.sql.execution.datasources.hbase").save()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/readwriter.py", line 593, in save
    self._jwrite.save()
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o152.save.
: java.util.NoSuchElementException: key not found: schemastring
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at org.apache.spark.sql.catalyst.util.CaseInsensitiveMap.default(CaseInsensitiveMap.scala:28)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at org.apache.spark.sql.catalyst.util.CaseInsensitiveMap.apply(CaseInsensitiveMap.scala:28)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$$anonfun$apply$3$$anonfun$11.apply(HBaseTableCatalog.scala:283)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$$anonfun$apply$3$$anonfun$11.apply(HBaseTableCatalog.scala:283)
        at scala.Option.map(Option.scala:146)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$$anonfun$apply$3.apply(HBaseTableCatalog.scala:283)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$$anonfun$apply$3.apply(HBaseTableCatalog.scala:281)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$.apply(HBaseTableCatalog.scala:281)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:80)
        at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:59)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:471)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:50)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:609)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:745)
