### ISSUE TITLE
NoSuchMethodError: org.apache.hadoop.hbase.client.Put.addColumn

### ISSUE THREAD

**Issue by Normal** [hortonworks-spark/shc#277]
Hi!

It ry to use shc-core to save dataframe into hbase via spark.
My versions:
hbase: 1.1.2.2.6.4.0-91
spark: 1.6
scala: 2.10
shc: 1.1.1-1.6-s_2.10

Configuration looks like that:

      val schema_array = s"""{"type": "array", "items": ["string","null"]}""".stripMargin

      def catalog: String = s"""{
                   |"table":{"namespace":"default", "name":"tblename"},
                   |"rowkey":"id",
                   |"columns":{
                   |"id":{"cf":"rowkey", "col":"id", "type":"string"},
                   |"col1":{"cf":"data", "col":"col1", "avro":"schema_array"}
                   |}
                   |}""".stripMargin 

      df
      .write
      .options(Map(
        "schema_array"-> schema_array,
        HBaseTableCatalog.tableCatalog -> catalog,
        HBaseTableCatalog.newTable -> "5"
      ))
      .format("org.apache.spark.sql.execution.datasources.hbase")
      .save()

it creates empty table and then fails with that:

.NoSuchMethodError: org.apache.hadoop.hbase.client.Put.addColumn([B[B[B)Lorg/apache/hadoop/hbase/client/Put;
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$1.apply(HBaseRelation.scala:217)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$1.apply(HBaseRelation.scala:216)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1(HBaseRelation.scala:216)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$insert$1.apply(HBaseRelation.scala:225)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$insert$1.apply(HBaseRelation.scala:225)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1112)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1277)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1119)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1091)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

But I see that inside my cat hbase client is the same version as hbase server.

**Comment by wahtdbogh** [comment]
@Normal I struggle with the same problem. Did you find the solution?

**Comment by Normal** [comment]
yes (sorry for the late response), the problem was that I have two different versions of hbase-client in my class path, one of them was causing this issue. Once I removed it, the issue goes away.

**Comment by wahtdbogh** [comment]
@Normal Thank you for your answer. Can you take a look on [this topic](https://stackoverflow.com/questions/56001027/real-time-kafka-data-ingestion-into-hbase-via-pyspark-java-lang-nosuchmethoder) where I described my problem? Do you have any suggestions what may be wrong?
