### ISSUE TITLE
Error reading hbase table with null values

### ISSUE THREAD

**Issue by amit-siddhu** [hortonworks-spark/shc#298]
Hi Team
I am getting an error while reading hbase table that contains some null column values. Details are as follows:

**Environment**
```
Spark version: 2.3.2
Scala version: 2.11.8
Java version: 1.8
Hbase version: 1.4.7
Setup: AWS EMR - emr-5.19.0
```

**Command**
```
sudo spark-shell --packages com.hortonworks:shc-core:1.1.1-2.1-s_2.11 --repositories http://repo.hortonworks.com/content/groups/public/
```

**Code**
```
import org.apache.spark.sql.{SQLContext, _}
import org.apache.spark.sql.execution.datasources.hbase._
import org.apache.spark.{SparkConf, SparkContext}
import spark.sqlContext.implicits._

def withCatalog(cat: String): DataFrame = {
  spark.sqlContext
  .read
  .options(Map(HBaseTableCatalog.tableCatalog->cat))
  .format("org.apache.spark.sql.execution.datasources.hbase")
  .load()
}

def catalog = s"""{
  |"table":{"namespace":"default", "name":"user"},
  |"rowkey":"id",
  |"columns":{
    |"id":{"cf":"rowkey", "col":"id", "type":"string"},
    |"username":{"cf":"user", "col":"username", "type":"string"},
    |"email":{"cf":"user", "col":"email", "type":"string"},
    |"first_name":{"cf":"user", "col":"first_name", "type":"string"},
    |"middle_name":{"cf":"user", "col":"middle_name", "type":"string"}
    |"last_name":{"cf":"user", "col":"last_name", "type":"string"}
  |}
|}""".stripMargin

val df = withCatalog(catalog)
```

**Error**
```
java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:347)
  at scala.None$.get(Option.scala:345)
  at org.apache.spark.sql.execution.datasources.hbase.Field.<init>(HBaseTableCatalog.scala:102)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$$anonfun$apply$3.apply(HBaseTableCatalog.scala:286)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$$anonfun$apply$3.apply(HBaseTableCatalog.scala:281)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$.apply(HBaseTableCatalog.scala:281)
  at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:80)
  at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:51)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
  at withCatalog(<console>:38)
  ... 55 elided
```

**Sample Hbase table data**
```
ROW            COLUMN+CELL
 10            column=user:id, timestamp=1544762764472, value=10
 10            column=user:username, timestamp=1544762764472, value=amitsiddhu
 10            column=user:email, timestamp=1544762764472, value=amit.siddhu7@gmail.com
 10            column=user:first_name, timestamp=1544762764472, value=Amit
 10            column=user:middle_name, timestamp=1544762764472, value=null
 10            column=user:last_name, timestamp=1544762764472, value=Siddhu
```

**My research**

Error is in HBaseTableCatalog.scala at line 102 =>
```
sType.map(CatalystSqlParser.parseDataType(_)).get
```
I tried changing it to =>
```
sType.map(CatalystSqlParser.parseDataType(_)).getOrElse(null)
```
But then i got following error:
```
java.lang.NullPointerException
  at org.apache.spark.sql.catalyst.expressions.objects.ValidateExternalType.<init>(objects.scala:1392)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$2.apply(RowEncoder.scala:183)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$2.apply(RowEncoder.scala:181)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
  at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$.org$apache$spark$sql$catalyst$encoders$RowEncoder$$serializerFor(RowEncoder.scala:181)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$.apply(RowEncoder.scala:61)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:75)
  at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:432)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:233)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
  at withCatalog(<console>:38)
  ... 55 elided
```

**Finally**

If i remove column 'middle_name' which contains null values, from defined catalog then everything works fine. Please help resolve this issue.

Thanks.

**Comment by amit-siddhu** [comment]
**Solution**

I found a work around to get rid of the error reading null values from hbase:

**Change**

HBaseTableCatalog.scala at line 102:
```
sType.map(CatalystSqlParser.parseDataType(_)).get
```
**To**
```
sType.map(CatalystSqlParser.parseDataType(_)) match {
    case Some(i) => i
    case None => NullType
 }
```
**And**

Add NullType case to val length:
```
val length: Int = {
  if (len == -1) {
    dt match {
      case BinaryType | StringType => -1
      case BooleanType => Bytes.SIZEOF_BOOLEAN
      case ByteType => 1
      case DoubleType => Bytes.SIZEOF_DOUBLE
      case FloatType => Bytes.SIZEOF_FLOAT
      case IntegerType => Bytes.SIZEOF_INT
      case LongType => Bytes.SIZEOF_LONG
      case ShortType => Bytes.SIZEOF_SHORT
      case NullType => 0
      case _ => -1
    }
  } else {
    len
  }
}
```
**Also**

Add case NullType to method fromBytes in file/class PrimitiveType.scala:
```
def fromBytes(src: HBaseType): Any = {
  if (f.isDefined) {
    f.get.dt match {
      case BooleanType => toBoolean(src)
      case ByteType => src(0)
      case DoubleType => Bytes.toDouble(src)
      case FloatType => Bytes.toFloat(src)
      case IntegerType => Bytes.toInt(src)
      case LongType => Bytes.toLong(src)
      case ShortType => Bytes.toShort(src)
      case StringType => toUTF8String(src, src.length)
      case BinaryType => src
      case NullType => null
      case _ => throw new UnsupportedOperationException(s"unsupported data type ${f.get.dt}")
    }
  } else {
    throw new UnsupportedOperationException(
      "PrimitiveType coder: without field metadata, " +
        "'fromBytes' conversion can not be supported")
  }
}
```
