### ISSUE TITLE
I got issue: ClassNotFoundException: org.apache.hadoop.hbase.filter.FilterList$Operator

### ISSUE THREAD

**Issue by nhha1602** [hortonworks-spark/shc#329]
Dear All,

I tried to run example: HBaseSource.scala example. but when i submit it, i got following errors:

Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.filter.FilterList$Operator

More detail as below. Please help to advise.
(I tried to find package that include method org.apache.hadoop.hbase.filter.FilterList$Operator, but did not find it)

2019-11-27 10:29:24 INFO  ExecutorAllocationManager:54 - New executor 0 has registered (new total is 1)
2019-11-27 10:29:24 INFO  TaskSetManager:54 - Starting task 0.0 in stage 0.0 (TID 0, 192.168.174.129, executor 0, partition 0, ANY, 9474 bytes)
2019-11-27 10:29:24 INFO  BlockManagerMasterEndpoint:54 - Registering block manager 192.168.174.129:44105 with 366.3 MB RAM, BlockManagerId(0, 192.168.174.129, 44105, None)
2019-11-27 10:29:24 WARN  TaskSetManager:66 - Lost task 0.0 in stage 0.0 (TID 0, 192.168.174.129, executor 0): java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/filter/FilterList$Operator
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1629)
        at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:79)
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:520)
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:494)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:494)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:391)
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:681)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:370)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.filter.FilterList$Operator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 38 more

**Comment by nhha1602** [comment]
I fixed this issue ...
Thank you.

**Comment by albho** [comment]
How did you fixed?
