### ISSUE TITLE
SHC is not working on Spark 1.6.2 and later

### ISSUE THREAD

**Issue by zroslaw** [hortonworks-spark/shc#48]
While trying to save Dataframe to HBase I'm getting an error 

```
Caused by: java.lang.IncompatibleClassChangeError: Found class org.apache.spark.sql.catalyst.expressions.MutableRow, but interface was expected
	at org.apache.spark.sql.execution.datasources.hbase.Utils$.setRowCol(Utils.scala:61)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD$$anonfun$buildRow$1.apply(HBaseTableScan.scala:120)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD$$anonfun$buildRow$1.apply(HBaseTableScan.scala:101)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD.buildRow(HBaseTableScan.scala:101)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD$$anon$3.next(HBaseTableScan.scala:190)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableScanRDD$$anon$3.next(HBaseTableScan.scala:180)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:140)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:130)
	at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:285)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:171)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

It seems like SHC does not support new versions of Catalyst API

Is there any quick fix or workaround for that issue?
Especially it is interesting for current version of Spark 1.6.2 in HDP 2.5.

**Comment by weiqingy** [comment]
Could you share your code? For Spark2.0.*, please refer to this branch: https://github.com/hortonworks-spark/shc/tree/branch-2.0 (but we donot support it right now).

**Comment by mkanchwala** [comment]
When will it be supported on Spark 2.x? What's the release date?

**Comment by weiqingy** [comment]
[Branch-2.1](https://github.com/hortonworks-spark/shc/tree/branch-2.1) of SHC, which is for Spark 2.1.x, will may be released in February.

**Comment by gmermoud** [comment]
@weiqingy I am seeing that branch-2.1 is still actively developed. When is the release planned?

**Comment by weiqingy** [comment]
Hi, @gmermoud  We'll make the release after finishing the ongoing feature of supporting multiple secure HBase clusters, so it'll be released in one month around.

**Comment by AtulKumVerma** [comment]
Hi @**weiqingy** ,
i want to use spark 1.6 version and java 7,  because of cluster environment setup so what version of shc should use for operation on hbase.

**Comment by weiqingy** [comment]
@AtulKumVerma 

You can use v1.1.1-1.6 (https://github.com/hortonworks-spark/shc/releases/tag/v1.1.1-1.6). This release has already been in Hortonoworks repo, so you can use it directly by adding the following in the command line:
```
--packages com.hortonworks:shc-core:1.1.1-1.6-s_2.10 --repositories http://repo.hortonworks.com/content/groups/public/ 
```
The corresponding branch is: https://github.com/hortonworks-spark/shc/tree/branch-1.6
