### ISSUE TITLE
unsupported data type FloatType

### ISSUE THREAD

**Issue by slyons** [hortonworks-spark/shc#74]
I'm trying to load data from one dataframe and write it to HBase. Whenever it tries to write it chokes on converting the types. Do I have to extract it all to case classes? I would much rather just use the Row types that come from Spark SQL.

**Comment by weiqingy** [comment]
You can refer [HBaseSource example](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseSource.scala) about how to save data into HBase with SHC. You donot need to "extract it all to case classes", but you need to define a `catalog` based on the dataframe schema. `catalog` is a mapping between HBase and Spark tables. 

The code below is to write the dataframe `df` into a HBase table:
```
df.write.options(
   Map(HBaseTableCatalog.tableCatalog -> catalog, HBaseTableCatalog.newTable -> "5"))
  .format("org.apache.spark.sql.execution.datasources.hbase")
  .save()
```

**Comment by weiqingy** [comment]
You do not need to "extract it all to case classes", but when you define the catalog, you may want to use Scala types "float" instead of Spark data types like "FloatType".

**Comment by slyons** [comment]
I have followed the instructions, I have a catalog defined and everything. 

`"ProductID":{"cf":"ProductIDCF", "col":"ProductID", "type":"int"},
 "TransactionDate":{"cf":"TransactionDateCF", "col":"TransactionDate", "type":"long"},
 "ChannelID":{"cf":"ChannelIDCF", "col":"ChannelID", "type":"int"},`
(Just a snippet)

`batch.write.options(
            Map(
              HBaseTableCatalog.tableCatalog -> myCat,
              HBaseTableCatalog.newTable -> "5"))
            .format("org.apache.spark.sql.execution.datasources.hbase")
            .save()`

This data is based on a RDD of JSON strings that is parsed into a DataFrame.

**Comment by weiqingy** [comment]
It looks fine. Could you please share the detailed error information? Is the error from "TransactionDate"?

**Comment by slyons** [comment]
It's from another column that I can't include in a snippet. I've had this error before with other types, like so:

`java.lang.Exception: unsupported data type LongType                                                                                                                          [88/9058]
        at org.apache.spark.sql.execution.datasources.hbase.Utils$.toBytes(Utils.scala:88)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$2.apply(HBaseRelation.scala:155)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$2.apply(HBaseRelation.scala:154)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)...`

**Comment by sanjaybigdata** [comment]
I got the same issue when one of the column with datatype long had null values.   
`unsupported data type LongType`    
using fillna(0) to replace null with 0 fixed the issue and I was able to write to hbase.

**Comment by Abhisrajput** [comment]
Hi,

I am having same error with timestamp

It says  **java.lang.Exception: unsupported data type TimestampType**

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 4, localhost): java.lang.Exception: unsupported data type DateType
        at org.apache.spark.sql.execution.datasources.hbase.Utils$.toBytes(Utils.scala:88)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$2.apply(HBaseRelation.scala:152)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation$$anonfun$org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1$2.apply(HBaseRelation.scala:151)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.org$apache$spark$sql$execution$datasources$hbase$HBaseRelation$$convertToPut$1(HBaseRelation.scala:151)
```
