### ISSUE TITLE
shc 2.11  - Catalogue loading fails 

### ISSUE THREAD

**Issue by tenstriker** [hortonworks-spark/shc#75]
I am using shc 2.11 with spark 2.0.1. In following example catalogue loading I am using sparkSession instead of sqlContext .  Looks like it tries to create a directory similar to my cwd on hdfs! Is there a way I can configure different temp directory for it? Also is this proper way to load catalogue with spark 2? 

`  def withCatalog(cat: String) = {
    sparkSession
    .read
    .options(Map(HBaseTableCatalog.tableCatalog -> cat))
    .format("org.apache.spark.sql.execution.datasources.hbase")
    .load
  }`

`Caused by: org.apache.spark.SparkException: Unable to create database default as failed to create its directory maprfs:///home/centos/myapp/spark-warehouse
	at org.apache.spark.sql.catalyst.catalog.InMemoryCatalog.liftedTree1$1(InMemoryCatalog.scala:114)
	at org.apache.spark.sql.catalyst.catalog.InMemoryCatalog.createDatabase(InMemoryCatalog.scala:108)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createDatabase(SessionCatalog.scala:147)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.<init>(SessionCatalog.scala:89)
	at org.apache.spark.sql.internal.SessionState.catalog$lzycompute(SessionState.scala:95)
	at org.apache.spark.sql.internal.SessionState.catalog(SessionState.scala:95)
	at org.apache.spark.sql.internal.SessionState$$anon$1.<init>(SessionState.scala:112)
	at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:112)
	at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:382)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:143)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
	at com.mypckg.DFInitializer.withCatalog(DFInitializer.scala:78)`

**Comment by weiqingy** [comment]
@tenstriker It's supposed to work if your code is written as [SHC examples](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseSource.scala). Both of SparkConf and sparkSession should work in the same way, but did you try`val sparkConf = new SparkConf()`?

**Comment by tenstriker** [comment]
@weiqingy I ran with both spark 1 and spark 2. I didn't ran into this issue with spark 1. I think with spark 1 it doesn't try to create temp database directory on hdfs. while with spark 2 it's trying to create inmemory catalog on hdfs  at hdfs:///home/centos/myapp/spark-warehouse. If I create a directory manually on hdfs and change it permission to 777 then it works with spark 2. So I just need to know how to change the path of the default catalogue directory.

**Comment by tenstriker** [comment]
I came across this JIRA https://issues.apache.org/jira/browse/SPARK-15034 . May be I can try that to change location of spark-warehouse to meaningful directory.

**Comment by weiqingy** [comment]
You may also want to try to configure the warehouse directory like the following:

` ``
SparkSession spark = SparkSession
      .builder()
      .appName("Java Spark Hive Example")
      .config("spark.sql.warehouse.dir", "spark-warehouse")
      .enableHiveSupport()
      .getOrCreate();
` ``
